CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_DEL_STAT_MLTPL_ROW]
@INT_ARRAY IntArrayTableType READONLY
AS
BEGIN

DELETE FROM HS_HR_IA_STAT_LEA_DRFT_INFO
WHERE TABLE_RECORD_ID IN (SELECT ID FROM @INT_ARRAY);

DELETE FROM HS_HR_IA_STATUTRY_LEAVE_UPLOAD
WHERE ID IN (SELECT ID FROM @INT_ARRAY);

END
GO