CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_INSRT_ND_GET_ID_CMN_CNFG]
@COLUMN_NO INT,
@DATA NVARCHAR(MAX)
AS
BEGIN

DECLARE @COLUMN_NAME NVARCHAR(200);
DECLARE @QUERY NVARCHAR(MAX);

SELECT @COLUMN_NAME = column_name
FROM (
  SELECT DISTINCT column_name,ordinal_position
  FROM information_schema.columns
  WHERE table_name = 'HS_HR_IA_COMMN_CONFG_UPLOAD'
) AS subquery
WHERE ordinal_position = @COLUMN_NO;

IF NOT EXISTS (SELECT 1 FROM HS_HR_IA_COMMN_CONFG_UPLOAD)
BEGIN
    -- Reset the identity column to a starting value (e.g., 1)
    DBCC CHECKIDENT ('HS_HR_IA_COMMN_CONFG_UPLOAD', RESEED, 1);
END

SET @QUERY='INSERT INTO [HS_HR_IA_COMMN_CONFG_UPLOAD] (['+@COLUMN_NAME+'])
OUTPUT INSERTED.ID
VALUES ('''+@DATA+''');'

EXEC(@QUERY)

END
GO