--Employee data
ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_NAMES_BY_INI varchar(200);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_NIC_NO varchar(20);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_BLOOD_GROUP varchar(20);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_BARCODENO varchar(20);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_PAYROLLNO varchar(20);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_EPF_EMPLOYEE_AMOUNT decimal(15, 2);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_EPF_EMPLOYER_AMOUNT decimal(15, 2);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_ETF_EMPLOYEE_AMOUNT decimal(15, 2);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_MSPS_EMPLOYER_AMOUNT decimal(15, 2);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_MSPS_EMPLOYEE_AMOUNT decimal(15, 2);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_PER_ADDRESS1 varchar(90);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_PER_ADDRESS2 varchar(90);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_PER_ADDRESS3 varchar(90);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_PER_CITY varchar(90);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_PER_TELEPHONE varchar(30);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_TEM_CITY varchar(90);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_TEM_TELEPHONE varchar(30);

ALTER TABLE HS_HR_IA_EMPLOYEE_UPLOAD ALTER COLUMN EMP_OFFICE_EXTN varchar(20);

--Dependent Info
ALTER TABLE HS_HR_IA_DEPINFO_UPLOAD ALTER COLUMN EREL_RELATIONFULLNAME varchar(200);

ALTER TABLE HS_HR_IA_DEPINFO_UPLOAD ALTER COLUMN EREL_IS_MARRIED numeric (1,0);

ALTER TABLE HS_HR_IA_DEPINFO_UPLOAD ALTER COLUMN EREL_IS_WORKING numeric (1,0);

--Emergency Contact
ALTER TABLE HS_HR_IA_EC_UPLOAD ALTER COLUMN EC_CONT_PER_FULLNAME varchar (200);

ALTER TABLE HS_HR_IA_EC_UPLOAD ALTER COLUMN EC_RELATIONSHIP_ORDER numeric (3, 0);


--Bank Details
ALTER TABLE HS_HR_IA_BANK_UPLOAD ALTER COLUMN EBANK_ACC_NO varchar (80);

ALTER TABLE HS_HR_IA_BANK_UPLOAD ALTER COLUMN ACCTYPE_ID varchar (20);

ALTER TABLE HS_HR_IA_BANK_UPLOAD ALTER COLUMN CURRENCY_SYMBOL varchar (20);


--Statutory leave
ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN ACTIVE smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN ALLOW_HALF_DAYS smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN HOLIDAY_AS_LEAVE smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN LIEU_LEAVE smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN MATERNITY_LEAVE smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN NO_PAY_LEAVE smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN SHOW_BALANCE numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN EARNED_CF_BREAK_DOWN smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN EXTENDED_PERIOD smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN ALLOW_PLANNING numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN ATTACHMENT_REQUIRED numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN VIEW_ADDITIONAL_FIELD numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN ALLOW_NEGATIVE numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN KIOSK_ALLOWED numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN HIDE_ZERO_ENTITLEMENT numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN ALLOW_SELECT_APPROVER numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN SHOW_LEAVE_REASON numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN CONSIDER_IN_DASHBOARD numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN SHOW_IN_OFFBOARDING numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN CONSIDER_FOR_TIME_LOST numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN COMMENT_MANDATORY numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN LONG_LEAVE smallint;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN HIDE_IN_SELF_APP bit;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN APPLY_SEQUENCE_IN_DASH numeric (1,0);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN MINIMUM_DAYS_IN_SNGLE_LEA_APP numeric (5,2);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN APPLY_TGTHER_WITH_LEA_TYPE varchar(6);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN FUTURE_LEAVE_UTILIZED_AS varchar(6);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN UTILIZATION_PERIOD int;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN FUTURE_LEAVE_TYPE_NAME varchar(6);

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD ALTER COLUMN NOTICE_PERIOD int;


--Short Leave
ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD ALTER COLUMN MIN_HOURS_ALLOWED float;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD ALTER COLUMN MAX_HOURS_ALLOWED float;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD ALTER COLUMN MAX_OCCURRENCE float;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD ALTER COLUMN LEAVE_TIME_PERIOD float;

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_EXCELNAME='Maximum Consecutive Days in a single leave application' WHERE COLUMN_ORDER=33 AND TEMPLATE_ID='temp6'

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DATATYPE='numeric' WHERE TEMPLATE_ID='temp7' AND COLUMN_ORDER=5