CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_CMN_CNF_APRV_STS]
@USER_ID NVARCHAR(40)
AS
BEGIN
DECLARE @QUERY NVARCHAR(MAX);
SET @QUERY= 'SELECT TOP 1 APPROVAL_STATUS FROM HS_HR_IA_CMN_CNFG_INFO a LEFT JOIN HS_HR_IA_COMMN_CONFG_DRFT_INFO b ON a.TABLE_ROW_ID=b.TABLE_RECORD_ID WHERE USER_ID='''+@USER_ID+''' ORDER BY APPROVAL_DATE DESC;'
EXEC(@QUERY)
END