CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_CMN_CNFG_RDIO_OPTNS] 
@QUESTION_NO int
AS
BEGIN
SELECT [OPTION_LABEL],[OPTION_VALUE] FROM [HS_HR_IA_COMN_CNFG_RADIO_OPTNS] WHERE QUESTION_NO=@QUESTION_NO
END
GO