CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_ABSNC_WIZ_QSTIONS]
@SUBSECTION_ID NVARCHAR(12)
AS
BEGIN
SELECT QUESTION_NO, QUESTION_STATEMENT, QUESTION_TYPE FROM HS_HR_IA_WIZARD_QUESTIONS WHERE SUBSECTION_ID=@SUBSECTION_ID
END