CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_UPDT_CMN_CNFG_MBL_IMG_NM]
@ID INT,
@MOBILE_LOGO_IMAGE_NAME NVARCHAR(MAX)
AS
BEGIN
UPDATE [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_UPLOAD] SET MOBILE_LOGO_IMAGE_NAME=@MOBILE_LOGO_IMAGE_NAME WHERE ID=@ID;
END
GO