CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_CMN_CNFG_RESPONSE]
@ID INT
AS
BEGIN

DECLARE @QUERY NVARCHAR(MAX);

SET @QUERY = 'SELECT PREFERRED_USERNAME,LOGO_IMAGE_NAME,IS_EMP_NUM_MANUALLY_ENTERED,MOBILE_LOGO_IMAGE_NAME,IS_REPORT_NAV_ENABLED,OTHER_CONFIGURATIONS FROM HS_HR_IA_COMMN_CONFG_UPLOAD  WHERE [ID] = ' + CAST(@ID as NVARCHAR) + ';'

EXEC(@QUERY)

END
GO