CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_UPDT_CMN_CNFG_UPLD_OPTN]
@ID INT,
@COLUMN_NO INT,
@DATA BIT
AS
BEGIN

DECLARE @COLUMN_NAME NVARCHAR(200);
DECLARE @QUERY NVARCHAR(MAX);
DECLARE @DATA_NVARCHAR NVARCHAR(2);

SELECT @COLUMN_NAME = column_name
FROM (
  SELECT column_name, ROW_NUMBER() OVER (ORDER BY ordinal_position) AS ordinal_position
  FROM information_schema.columns
  WHERE table_name = 'HS_HR_IA_COMMN_CONFG_UPLOAD'
) AS subquery
WHERE ordinal_position = @COLUMN_NO;

SET @DATA_NVARCHAR = CONVERT(NVARCHAR(MAX), @DATA, 1);


SET @QUERY='UPDATE [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_UPLOAD] SET ['+@COLUMN_NAME+'] = '+@DATA_NVARCHAR+' WHERE [ID]='+CAST(@ID as nvarchar)+';'

EXEC(@QUERY)

END
GO