CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_INSRT_IN_CMN_CNFG_INFO] 
@APPROVAL_STATUS varchar(50),
@APPROVAL_BY nvarchar(20),
@APPROVAL_COMMENT varchar(500),
@APPROVAL_SIGNATURE varchar(200),
@APPROVAL_DATE datetime,
@SIGNOFF_DATA varbinary(max),
@TABLE_ROW_ID INT

AS
BEGIN
IF NOT EXISTS(SELECT 1 FROM HS_HR_IA_CMN_CNFG_INFO)
BEGIN
	DBCC CHECKIDENT ('[HS_HR_IA_CMN_CNFG_INFO]', RESEED, 1);
END;

INSERT INTO [QADBV9_L2].[HS_HR_IA_CMN_CNFG_INFO]
           ([APPROVAL_STATUS]
           ,[APPROVAL_BY]
           ,[APPROVAL_COMMENT]
           ,[APPROVAL_SIGNATURE]
           ,[APPROVAL_DATE],
		   [SIGNOFF_DATA],
		   [TABLE_ROW_ID])
     VALUES
           (@APPROVAL_STATUS
           ,@APPROVAL_BY
           ,@APPROVAL_COMMENT
           ,@APPROVAL_SIGNATURE
           ,@APPROVAL_DATE
		   ,@SIGNOFF_DATA
		   ,@TABLE_ROW_ID)
END
GO
