CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_INSRT_CMN_CNFG_DRAFT]
@USER_ID nvarchar(50),
@TABLE_RECORD_ID int,
@IS_DRAFT bit,
@DATE_TIME Datetime
AS
BEGIN

INSERT INTO HS_HR_IA_COMMN_CONFG_DRFT_INFO VALUES (@USER_ID,@TABLE_RECORD_ID,@IS_DRAFT,@DATE_TIME)

END
GO