CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_SHRT_LEA_RESPONSE]
@ID INT
AS
BEGIN

DECLARE @QUERY NVARCHAR(MAX);

SET @QUERY = 'SELECT [SHORT_LEAVE_TYPE_CODE]
      ,[LEAVE_TYPE_NAME]
      ,[MIN_HOURS_ALLOWED]
      ,[MAX_HOURS_ALLOWED]
      ,[MAX_OCCURRENCE]
      ,[MAX_CONSECUTIVE_HOURS_ALLOWED]
      ,[CONSIDER_ALL_LEAVE_TYPES]
      ,[MAX_NO_OF_LEAVE_PER_DAY]
      ,[LEAVE_TIME_PERIOD]
      ,[DURATION_PER_SLOT_BEG_OF_SHIFT]
      ,[DURATION_PER_SLOT_END_OF_SHIFT]
      ,[MAX_HOURS_PER_MONTH]
      ,[MAX_HOURS_PER_YEAR]
      ,[APPLICABLE_FOR_WEEKLY]
      ,[LEAVE_NEED_APPROVAL]
      ,[ENTITLEMENT_CONFIRMED_EMP]
      ,[ENTITLEMENT_UN_CONFIRMED_EMP]
      ,[COMMENTS] FROM HS_HR_IA_SHORT_LEAVE_UPLOAD WHERE [ID] = ' + CAST(@ID as NVARCHAR) + ';'

EXEC(@QUERY)

END
GO