CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_UPDT_CMN_CNFG_IMG_NAME]
@ID INT,
@LOGO_IMAGE_NAME NVARCHAR(MAX)
AS
BEGIN
UPDATE [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_UPLOAD] SET LOGO_IMAGE_NAME=@LOGO_IMAGE_NAME WHERE ID=@ID;
END
GO