ALTER PROCEDURE [QADBV9_L2].[SP_IA_INSRT_IN_IA_DASHBRD_INFO] 
@MODULE_ID INT,
@SUBSECTION_ID nvarchar(6),
@APPROVAL_STATUS varchar(50),
@APPROVAL_BY nvarchar(20),
@APPROVAL_COMMENT varchar(500),
@APPROVAL_SIGNATURE varchar(200),
@APPROVAL_DATE datetime,
@APPROVAL_DATA varbinary(max),
@SIGNOFF_DATA varbinary(max)

AS
BEGIN
IF(NOT EXISTS(SELECT 1 FROM HS_HR_IA_DASHBOARD_INFO))
BEGIN
	DBCC CHECKIDENT ('[HS_HR_IA_DASHBOARD_INFO]', RESEED, 0);
END;

INSERT INTO [QADBV9_L2].[HS_HR_IA_DASHBOARD_INFO]
           ([MODULE_ID]
           ,[SUBSECTION_ID]
           ,[APPROVAL_STATUS]
           ,[APPROVAL_BY]
           ,[APPROVAL_COMMENT]
           ,[APPROVAL_SIGNATURE]
           ,[APPROVAL_DATE]
		   ,[APPROVAL_DATA],
		   [SIGNOFF_DATA])
     VALUES
           (@MODULE_ID
           ,@SUBSECTION_ID
           ,@APPROVAL_STATUS
           ,@APPROVAL_BY
           ,@APPROVAL_COMMENT
           ,@APPROVAL_SIGNATURE
           ,@APPROVAL_DATE
		   ,@APPROVAL_DATA,
		   @SIGNOFF_DATA)
END
GO
