ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_DASHBOARD_DATA_GROUP]
@PAGE_INDEX INT,
@PAGE_SIZE INT,
@SEARCH_TEXT NVARCHAR(MAX),
@ORDER_BY NVARCHAR(MAX),
@MODULE_NAME NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;      
    DECLARE @SQL NVARCHAR(MAX);      
    DECLARE @FINAL_QUERY NVARCHAR(MAX);         
    DECLARE @WHERE_CLS NVARCHAR(MAX);  
    DECLARE @ORDER_CLS NVARCHAR(MAX);
	DECLARE @MODIFIED_ORDER_BY NVARCHAR(50);
    DECLARE @S NVARCHAR(MAX);       
    SET @FINAL_QUERY = N'';         
    SET @WHERE_CLS = N'';

	IF(@SEARCH_TEXT <> '')      
    BEGIN       
        SET @WHERE_CLS = @WHERE_CLS + N'AND (MODULE_NAME LIKE ''%' + @SEARCH_TEXT + N'%'' OR SUBSECTION_NAME LIKE ''%' + @SEARCH_TEXT + N'%'' OR APPROVAL_STATUS LIKE ''%' +@SEARCH_TEXT+N'%'' OR APPROVAL_BY LIKE ''%' + @SEARCH_TEXT + N'%'')';      
    END

	IF(@ORDER_BY <> '')      
    BEGIN
		SELECT @MODIFIED_ORDER_BY = 
			CASE 
				WHEN CHARINDEX('ID', @ORDER_BY) > 0 
				THEN REPLACE(@ORDER_BY, '_ID', '_NAME')
				ELSE @ORDER_BY 
			END 
        SET @ORDER_CLS =  N'ORDER BY ' + @MODIFIED_ORDER_BY
	END

	SET @FINAL_QUERY=N'
	DECLARE @TOTAL_COUNT INT;      
    DECLARE @RECORD_COUNT INT;

SELECT RECORD_ID,MODULE_NAME, SUBSECTION_NAME, APPROVAL_STATUS, APPROVAL_BY, APPROVAL_DATE,VENDOR_APPROVAL_STATUS,VENDOR_APPROVAL_BY into #temp1 from (
SELECT a.[SUBSECTION_ID],
		a.[SUBSECTION_NAME],
      a.[MODULE_ID],
	  d.[MODULE_NAME],
	  b.[APPROVAL_STATUS],
	  b.[APPROVAL_BY],
	  b.[RECORD_ID],
	  c.[VENDOR_APPROVAL_BY],
	  c.[VENDOR_APPROVAL_STATUS],
	  b.[APPROVAL_DATE],
	  ROW_NUMBER() over (partition by a.[SUBSECTION_ID] order by a.[SUBSECTION_ID], b.[APPROVAL_DATE] desc) data_num
  FROM [HS_HR_IA_SUBSECTIONS] a 
  LEFT JOIN [HS_HR_IA_DASHBOARD_INFO] b ON a.SUBSECTION_ID=b.SUBSECTION_ID 
  LEFT JOIN HS_HR_IA_VENDOR_APPROVAL_INFO c ON b.RECORD_ID=c.USER_RECORD_ID
  LEFT JOIN HS_HR_IA_MODULES d ON a.MODULE_ID=d.MODULE_ID
  ) x
  where x.data_num = 1 AND x.MODULE_NAME='''+@MODULE_NAME+'''

	SELECT * INTO #temp2
	FROM #temp1 WHERE 1=1 '+@WHERE_CLS+';

   	SELECT RECORD_ID, MODULE_NAME, SUBSECTION_NAME, APPROVAL_STATUS, APPROVAL_BY,VENDOR_APPROVAL_STATUS, VENDOR_APPROVAL_BY into #temp3
    FROM (
        SELECT *,
            ROW_NUMBER() OVER ( ' +@ORDER_CLS+ ' ) RecordID
        FROM #temp2 as A)
		as PagedData
   WHERE RecordID BETWEEN (('+convert(nvarchar,@PAGE_INDEX)+' - 1) * '+convert(nvarchar,@PAGE_SIZE)+'  + 1)          
   AND ('  +convert(nvarchar,@PAGE_INDEX)+' * '+convert(nvarchar,@PAGE_SIZE)+');
   
	SELECT @TOTAL_COUNT=COUNT(*) FROM #temp1;


	SELECT @RECORD_COUNT=COUNT(*) FROM #temp2;

	SELECT *, @TOTAL_COUNT,@RECORD_COUNT from #temp3;
	
	DROP TABLE #temp1;
	DROP TABLE #temp2;
	DROP TABLE #temp3;';
	PRINT(@FINAL_QUERY);
	EXEC(@FINAL_QUERY);
END
GO
