CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_WZRD_DRPDWN_OPTIONS] 
@MODULE_ID int, 
@SUBSECTION_ID nvarchar(6), 
@QUESTION_NO int
AS
BEGIN
SELECT [ANSWER_OPTION] FROM [HS_HR_IA_WIZARD_DRPDWN_OPTNS] WHERE SUBSECTION_ID=@SUBSECTION_ID AND MODULE_ID=@MODULE_ID AND QUESTION_NO=@QUESTION_NO
END
GO