if  EXISTS (select * from sysobjects where [name] ='SP_AI_UPLOAD_EMPLOYEE')
drop  PROCEDURE SP_AI_UPLOAD_EMPLOYEE
go

CREATE PROCEDURE SP_AI_UPLOAD_EMPLOYEE
AS 
BEGIN
DECLARE @EMPLOYEEID AS VARCHAR(8)
DECLARE @ROW_NUM NUMERIC(12)
DECLARE @CursorAttribute CURSOR SET @CursorAttribute = CURSOR FAST_FORWARD
FOR
SELECT ROW_NUMBER() OVER (
		ORDER BY (
				SELECT 0
				)
		) AS ROW_NUM
	,EMP_NUMBER
FROM HS_HR_IA_EMPLOYEE_UPLOAD

OPEN @CursorAttribute
FETCH NEXT
FROM @CursorAttribute
INTO @ROW_NUM
	,@EMPLOYEEID
WHILE @@FETCH_STATUS = 0
BEGIN

BEGIN TRY  

--Get Max Employee Number From HS_HR_EMPLOYEE 
DECLARE @MAX_EMP_NUMBER VARCHAR(8) 
 
SET @MAX_EMP_NUMBER = (SELECT RIGHT('00000000' + CAST(COALESCE(MAX(CAST (EMP_NUMBER as integer)),0)+1  AS VARCHAR),8) AS EMP_NUMBER FROM HS_HR_EMPLOYEE)

--Set Employee display name 
DECLARE @EMPLOYEE_DISPLAY_NAME VARCHAR(600) 
DECLARE @CALLING_NAME VARCHAR(50) 
DECLARE @SURNAME VARCHAR(50) 

SET @CALLING_NAME = (SELECT EMP_CALLING_NAME FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
SET @SURNAME=(SELECT EMP_SURNAME FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
SET @EMPLOYEE_DISPLAY_NAME = COALESCE(@CALLING_NAME,'') + '''' +  COALESCE(@SURNAME,'') 


-- insert title
IF (SELECT EMP_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL 
BEGIN
If Not Exists(select * from HS_HR_SALUTATION where SALU_CODE=(SELECT EMP_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_SALUTATION]
           ([SALU_CODE]
           ,[SALU_ID]
           ,[SALU_NAME]
           ,[SALU_GENDER]
           ,[SALU_GENDER_VALIDATION_FLG]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT EMP_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(SALU_ID),'0')+1),6) AS SALU_ID FROM HS_HR_SALUTATION)
           ,(SELECT EMP_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,0
           ,0
           ,NULL)
End
END

DECLARE @EMP_TITLE_CODE VARCHAR(10)
SET @EMP_TITLE_CODE = (select SALU_CODE from HS_HR_SALUTATION where SALU_CODE=(SELECT EMP_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert gender
IF (SELECT EMP_GENDER FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_GENDER where GEN_NAME=(SELECT EMP_GENDER FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_GENDER]
           ([GEN_CODE]
           ,[GEN_NAME]
           ,[GEN_DESC]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT isnull(MAX(GEN_CODE),'0')+1 AS GEN_CODE FROM HS_HR_GENDER)
           ,(SELECT EMP_GENDER FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EMP_GENDER FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,NULL)
End
END

DECLARE @EMP_GENDER_CODE VARCHAR(6) 
SET @EMP_GENDER_CODE = (select GEN_CODE from HS_HR_GENDER where GEN_NAME=(SELECT EMP_GENDER FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert NATIONALITY
IF (SELECT NATIONALITY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_NATIONALITY where NAT_NAME=(SELECT NATIONALITY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_NATIONALITY]
           ([NAT_CODE]
           ,[NAT_NAME]
           ,[DBGROUP_ID]
		   ,[NAT_CODE_REF])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(NAT_CODE),'0')+1),6) AS NAT_CODE FROM HS_HR_NATIONALITY)
           ,(SELECT NATIONALITY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,NULL
		   ,NULL)
End
END

DECLARE @NAT_CODE VARCHAR(6) 
SET @NAT_CODE = (select NAT_CODE from HS_HR_NATIONALITY where NAT_NAME=(SELECT NATIONALITY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert Religion
IF (SELECT RELIGION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_RELIGION where RLG_NAME=(SELECT RELIGION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_RELIGION]
           ([RLG_CODE]
           ,[RLG_NAME]
           ,[DBGROUP_ID]
		   ,[RLG_CODE_REF])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(RLG_CODE),'0')+1),6) AS RLG_CODE FROM HS_HR_RELIGION)
           ,(SELECT RELIGION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,NULL
		   ,NULL)
End
END

DECLARE @RLG_CODE VARCHAR(6) 
SET @RLG_CODE = (select RLG_CODE from HS_HR_RELIGION where RLG_NAME=(SELECT RELIGION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)); 

-- insert Blood group
IF (SELECT EMP_BLOOD_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_BLOOD_GROUP where BLGRP_NAME=(SELECT EMP_BLOOD_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_BLOOD_GROUP]
           ([BLGRP_CODE]
           ,[BLGRP_ID]
		   ,[BLGRP_NAME]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT EMP_BLOOD_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(BLGRP_ID),'0')+1),6) AS BLGRP_ID FROM HS_HR_BLOOD_GROUP)
           ,(SELECT EMP_BLOOD_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,NULL)
End
END

DECLARE @EMP_BLOOD_GROUP_CODE VARCHAR(6) 
SET @EMP_BLOOD_GROUP_CODE = (select BLGRP_CODE from HS_HR_BLOOD_GROUP where BLGRP_NAME=(SELECT EMP_BLOOD_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))


-- insert marital status
IF (SELECT EMP_MARITAL_STATUS FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_MARITAL_STATUS where MARST_NAME=(SELECT EMP_MARITAL_STATUS FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_MARITAL_STATUS]
           ([MARST_CODE]
           ,[MARST_ID]
		   ,[MARST_NAME]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT EMP_MARITAL_STATUS FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(MARST_ID),'0')+1),6) AS MARST_ID FROM HS_HR_MARITAL_STATUS)
           ,(SELECT EMP_MARITAL_STATUS FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,NULL)
End
END

DECLARE @EMP_MARITAL_STATUS_CODE VARCHAR(20)
SET @EMP_MARITAL_STATUS_CODE = (select MARST_CODE from HS_HR_MARITAL_STATUS where MARST_NAME=(SELECT EMP_MARITAL_STATUS FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert country
IF (SELECT EMP_PER_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_COUNTRY where COU_NAME=(SELECT EMP_PER_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_COUNTRY]
           ([COU_CODE]
           ,[COU_NAME]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('00000'+ CONVERT(VARCHAR,isnull(MAX(COU_CODE),'0')+1),6) AS COU_CODE FROM HS_HR_COUNTRY)
		   ,(SELECT EMP_PER_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,NULL)
End
END

DECLARE @EMP_PER_COUNTRY VARCHAR(6) 
SET @EMP_PER_COUNTRY = (select COU_CODE from HS_HR_COUNTRY where COU_NAME=(SELECT EMP_PER_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert country
IF (SELECT EMP_TEM_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_COUNTRY where COU_NAME=(SELECT EMP_TEM_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_COUNTRY]
           ([COU_CODE]
           ,[COU_NAME]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('00000'+ CONVERT(VARCHAR,isnull(MAX(COU_CODE),'0')+1),6) AS COU_CODE FROM HS_HR_COUNTRY)
		   ,(SELECT EMP_TEM_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,NULL)
End
END

DECLARE @EMP_TEM_COUNTRY VARCHAR(6) 
SET @EMP_TEM_COUNTRY = (select COU_CODE from HS_HR_COUNTRY where COU_NAME=(SELECT EMP_TEM_COUNTRY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert province
IF (SELECT EMP_PER_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_PROVINCE where PROVINCE_NAME=(SELECT EMP_PER_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_PROVINCE]
           ([PROVINCE_CODE]
           ,[PROVINCE_NAME]
		   ,[COU_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(PROVINCE_CODE),'0')+1),6) AS PROVINCE_CODE FROM HS_HR_PROVINCE)
		   ,(SELECT EMP_PER_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@EMP_PER_COUNTRY
		   ,NULL) 
End
END
DECLARE @EMP_PER_PROVINCE VARCHAR(6) 
SET @EMP_PER_PROVINCE = (select PROVINCE_CODE from HS_HR_PROVINCE where PROVINCE_NAME=(SELECT EMP_PER_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert province
IF (SELECT EMP_TEM_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_PROVINCE where PROVINCE_NAME=(SELECT EMP_TEM_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_PROVINCE]
           ([PROVINCE_CODE]
           ,[PROVINCE_NAME]
		   ,[COU_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(PROVINCE_CODE),'0')+1),6) AS PROVINCE_CODE FROM HS_HR_PROVINCE)
		   ,(SELECT EMP_TEM_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@EMP_TEM_COUNTRY
		   ,NULL)
End
END
DECLARE @EMP_TEM_PROVINCE VARCHAR(6) 
SET @EMP_TEM_PROVINCE = (select PROVINCE_CODE from HS_HR_PROVINCE where PROVINCE_NAME=(SELECT EMP_TEM_PROVINCE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))


-- insert distric
IF (SELECT EMP_PER_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_DISTRICT where DISTRICT_NAME=(SELECT EMP_PER_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_DISTRICT]
           ([DISTRICT_CODE]
           ,[DISTRICT_NAME]
		   ,[PROVINCE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(DISTRICT_CODE),'0')+1),6) AS DISTRICT_CODE FROM HS_HR_DISTRICT)
		   ,(SELECT EMP_PER_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@EMP_PER_PROVINCE
		   ,NULL)
End
END
DECLARE @EMP_PER_DISTRICT VARCHAR(6) 
SET @EMP_PER_DISTRICT = (select DISTRICT_CODE from HS_HR_DISTRICT where DISTRICT_NAME=(SELECT EMP_PER_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))


-- insert distric
IF (SELECT EMP_TEM_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_DISTRICT where DISTRICT_NAME=(SELECT EMP_TEM_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_DISTRICT]
           ([DISTRICT_CODE]
           ,[DISTRICT_NAME]
		   ,[PROVINCE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(DISTRICT_CODE),'0')+1),6) AS DISTRICT_CODE FROM HS_HR_DISTRICT)
		   ,(SELECT EMP_TEM_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@EMP_TEM_PROVINCE
		   ,NULL)
End
END
DECLARE @EMP_TEM_DISTRICT VARCHAR(6) 
SET @EMP_TEM_DISTRICT = (select DISTRICT_CODE from HS_HR_DISTRICT where DISTRICT_NAME=(SELECT EMP_TEM_DISTRICT FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert electorate
IF (SELECT EMP_PER_ELECTORATE_CODE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_ELECTORATE where ELECTORATE_NAME=(SELECT EMP_PER_ELECTORATE_CODE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_ELECTORATE]
           ([ELECTORATE_CODE]
           ,[ELECTORATE_NAME]
		   ,[DISTRICT_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(ELECTORATE_CODE),'0')+1),6) AS ELECTORATE_CODE FROM HS_HR_ELECTORATE)
		   ,(SELECT EMP_PER_ELECTORATE_CODE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@EMP_PER_DISTRICT
		   ,NULL)
End
END
DECLARE @EMP_PER_ELECTORATE_CODE VARCHAR(6) 
SET @EMP_PER_ELECTORATE_CODE = (select ELECTORATE_CODE from HS_HR_ELECTORATE where ELECTORATE_NAME=(SELECT EMP_PER_ELECTORATE_CODE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))


-- insert electorate
IF (SELECT EMP_TEM_ELECTORATE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_ELECTORATE where ELECTORATE_NAME=(SELECT EMP_TEM_ELECTORATE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_ELECTORATE]
           ([ELECTORATE_CODE]
           ,[ELECTORATE_NAME]
		   ,[DISTRICT_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT  RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(ELECTORATE_CODE),'0')+1),6) AS ELECTORATE_CODE FROM HS_HR_ELECTORATE)
		   ,(SELECT EMP_TEM_ELECTORATE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@EMP_TEM_DISTRICT
		   ,NULL)
End
END
DECLARE @EMP_TEM_ELECTORATE VARCHAR(6) 
SET @EMP_TEM_ELECTORATE = (select ELECTORATE_CODE from HS_HR_ELECTORATE where ELECTORATE_NAME=(SELECT EMP_TEM_ELECTORATE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert location
IF (SELECT LOCATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_LOCATION where LOC_NAME=(SELECT LOCATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_LOCATION]
           ([LOC_CODE]
           ,[LOC_NAME]
		   ,[COU_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(LOC_CODE),'0')+1),6) AS LOC_CODE FROM HS_HR_LOCATION)
		   ,(SELECT LOCATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,@EMP_PER_COUNTRY
		   ,NULL)
End
END

DECLARE @LOCATION_CODE VARCHAR(6) 
SET @LOCATION_CODE = (select LOC_CODE from HS_HR_LOCATION where LOC_NAME=(SELECT LOCATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert HIE_CODE 1
IF (SELECT HIE_LEVEL_1 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_1 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='1')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('1','Group')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_1 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,NULL
		   ,1
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_1 VARCHAR(6) 
SET @HIE_LEVEL_1 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_1 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert HIE_CODE 2
IF (SELECT HIE_LEVEL_2 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_2 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=2)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='2')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('2','Sector')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_2 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_1
		   ,2
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_2 VARCHAR(6) 
SET @HIE_LEVEL_2 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_2 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=2)

-- insert HIE_CODE 3
IF (SELECT HIE_LEVEL_3 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_3 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=3)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='3')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('3','Company')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_3 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_2
		   ,3
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_3 VARCHAR(6) 
SET @HIE_LEVEL_3 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_3 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=3)

-- insert HIE_CODE 4
IF (SELECT HIE_LEVEL_4 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_4 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=4)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='4')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('4','Division')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_4 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_3
		   ,4
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_4 VARCHAR(6) 
SET @HIE_LEVEL_4 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_4 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=4)

-- insert HIE_CODE 5
IF (SELECT HIE_LEVEL_5 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_5 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=5)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='5')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('5','Department')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_5 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_4
		   ,5
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_5 VARCHAR(6) 
SET @HIE_LEVEL_5 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_5 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=5)

-- insert HIE_CODE 6
IF (SELECT HIE_LEVEL_6 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_6 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=6)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='6')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('6','Sub Department')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_6 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_5
		   ,6
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_6 VARCHAR(6) 
SET @HIE_LEVEL_6 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_6 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=6)

-- insert HIE_CODE 7
IF (SELECT HIE_LEVEL_7 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_7 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=7)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='7')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('7','Unit')
	end

INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_7 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_6
		   ,7
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_7 VARCHAR(6) 
SET @HIE_LEVEL_7 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_7 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=7)

-- insert HIE_CODE 8
IF (SELECT HIE_LEVEL_8 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_8 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=8)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='8')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('8','Sub Unit')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_8 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_7
		   ,8
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_8 VARCHAR(6) 
SET @HIE_LEVEL_8 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_8 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=8)

-- insert HIE_CODE 9
IF (SELECT HIE_LEVEL_9 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_9 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) AND DEF_LEVEL=9)
Begin
	If Not Exists(select * from HS_HR_COMPANY_HIERARCHY_DEF where DEF_LEVEL='9')
	begin
		INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF(DEF_LEVEL,DEF_NAME) VALUES('9','Team')
	end
INSERT INTO [HS_HR_COMPANY_HIERARCHY]
           ([HIE_CODE]
           ,[HIE_NAME]
		   ,[HIE_RELATIONSHIP]
           ,[DEF_LEVEL]
		   ,[LOC_CODE]
		   ,[HIE_ISACTIVE_FLG])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(HIE_CODE),'0')+1),6) AS MARST_ID FROM HS_HR_COMPANY_HIERARCHY)
           ,(SELECT HIE_LEVEL_9 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_8
		   ,9
		   ,@LOCATION_CODE
		   ,1)
End
END

DECLARE @HIE_LEVEL_9 VARCHAR(6) 
SET @HIE_LEVEL_9 = (select HIE_CODE from HS_HR_COMPANY_HIERARCHY where HIE_NAME=(SELECT HIE_LEVEL_9 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)AND DEF_LEVEL=9)


-- insert salary grade
IF (SELECT SAL_GRD FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_PR_SALARY_GRADE where SAL_GRD_NAME=(SELECT SAL_GRD FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_PR_SALARY_GRADE]
           ([SAL_GRD_CODE]
           ,[SAL_GRD_NAME]
		   ,[HIE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(SAL_GRD_CODE),'0')+1),6) AS SAL_GRD_CODE FROM HS_PR_SALARY_GRADE)
		   ,(SELECT SAL_GRD FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,@HIE_LEVEL_1
		   ,NULL)
End
END

DECLARE @SAL_GRD_CODE VARCHAR(6) 
SET @SAL_GRD_CODE = (select SAL_GRD_CODE from HS_PR_SALARY_GRADE where SAL_GRD_NAME=(SELECT SAL_GRD FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert corporate title
IF (SELECT CORPORATE_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_CORPORATE_TITLE where CT_NAME=(SELECT CORPORATE_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_CORPORATE_TITLE]
           ([CT_CODE]
           ,[CT_NAME]
		   ,[CT_TOPLEV_FLG]
		   ,[CT_HEADS_FLG]
		   ,[CT_HEADS_COUNT]
		   ,[SAL_GRD_CODE]
		   ,[MANAGE_POS]
		   ,[HIE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(CT_CODE),'0')+1),6) AS CT_CODE FROM HS_HR_CORPORATE_TITLE)
		   ,(SELECT CORPORATE_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,0
		   ,0
		   ,0
		   ,@SAL_GRD_CODE
		   ,0
           ,@HIE_LEVEL_1
		   ,NULL)
End
END

DECLARE @CORPORATE_TITLE_CODE VARCHAR(6) 
SET @CORPORATE_TITLE_CODE = (select CT_CODE from HS_HR_CORPORATE_TITLE where CT_NAME=(SELECT CORPORATE_TITLE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert designation
IF (SELECT DESIGNATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN 
If Not Exists(select * from HS_HR_DESIGNATION where DSG_NAME=(SELECT DESIGNATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_DESIGNATION]
           ([DSG_CODE]
           ,[DSG_NAME]
		   ,[CT_CODE]
		   ,[DSG_SNRMGT_FLG]
		   ,[HIE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(DSG_CODE),'0')+1),6) AS DSG_CODE FROM HS_HR_DESIGNATION)
		   ,(SELECT DESIGNATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@CORPORATE_TITLE_CODE
		   ,0
           ,@HIE_LEVEL_1
		   ,NULL)
End
END

DECLARE @DESIGNATION VARCHAR(6) 
SET @DESIGNATION = (select DSG_CODE from HS_HR_DESIGNATION where DSG_NAME=(SELECT DESIGNATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert cost center
IF (SELECT COST_CENTRE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_PR_COST_CENTRE where CENTRE_NAME=(SELECT COST_CENTRE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_PR_COST_CENTRE]
           ([CENTRE_CODE]
           ,[CENTRE_NAME]
		   ,[HIE_CODE]
		   ,[CENTRE_DESCRIPTION]
           ,[DBGROUP_ID]
		   ,[CENTRE_DESC])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(CENTRE_CODE),'0')+1),6) AS CENTRE_CODE FROM HS_PR_COST_CENTRE)
		   ,(SELECT COST_CENTRE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,@HIE_LEVEL_1
		   ,NULL
		   ,NULL
		   ,NULL)
End
END

DECLARE @COST_CENTRE_CODE VARCHAR(6) 
SET @COST_CENTRE_CODE = (select CENTRE_CODE from HS_PR_COST_CENTRE where CENTRE_NAME=(SELECT COST_CENTRE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))



-- insert employee type
IF (SELECT EMP_TYPE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_EMPTYPE where EMPT_TYPEDESCRIPTION=(SELECT EMP_TYPE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_EMPTYPE]
           ([EMPT_ISDATELIMITED_FLG]
           ,[EMPT_TYPEDESCRIPTION]
		   ,[EMPT_TYPE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ('0'
		   ,(SELECT EMP_TYPE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(EMPT_TYPE_CODE),'0')+1),6) AS EMPT_TYPE_CODE FROM HS_HR_EMPTYPE)
		   ,NULL)
End
END

DECLARE @EMP_TYPE_CODE VARCHAR(6) 
SET @EMP_TYPE_CODE = (select EMPT_TYPE_CODE from HS_HR_EMPTYPE where EMPT_TYPEDESCRIPTION=(SELECT EMP_TYPE FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert staff category
IF (SELECT RECR_COMPANY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_STAFFCAT where STAFFCAT_NAME=(SELECT RECR_COMPANY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_STAFFCAT]
           ([STAFFCAT_NAME]
           ,[STAFFCAT_CODE]
		   ,[HIE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RECR_COMPANY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(STAFFCAT_CODE),'0')+1),6) AS STAFFCAT_CODE FROM HS_HR_STAFFCAT)
		   ,@HIE_LEVEL_1
		   ,NULL)
End
END

DECLARE @RECR_COMPANY_CODE VARCHAR(6) 
SET @RECR_COMPANY_CODE = (select STAFFCAT_CODE from HS_HR_STAFFCAT where STAFFCAT_NAME=(SELECT RECR_COMPANY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert employee category
IF (SELECT EMP_CATEGORY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_CATEGORY where CAT_NAME=(SELECT EMP_CATEGORY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_CATEGORY]
           ([CAT_CODE]
           ,[CAT_NAME]
		   ,[HIE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(CAT_CODE),'0')+1),6) AS CAT_CODE FROM HS_HR_CATEGORY)
		   ,(SELECT EMP_CATEGORY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_1
		   ,NULL)
End
END

DECLARE @EMP_CATEGORY_CODE VARCHAR(6) 
SET @EMP_CATEGORY_CODE = (select CAT_CODE from HS_HR_CATEGORY where CAT_NAME=(SELECT EMP_CATEGORY FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert employee group
IF (SELECT EMP_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_GROUP where GP_NAME=(SELECT EMP_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_GROUP]
           ([GP_CODE]
           ,[GP_NAME]
		   ,[HIE_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(GP_CODE),'0')+1),6) AS GP_CODE FROM HS_HR_GROUP)
		   ,(SELECT EMP_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@HIE_LEVEL_1
		   ,NULL)
End
END

DECLARE @EMP_GROUP_CODE VARCHAR(6) 
SET @EMP_GROUP_CODE = (select GP_CODE from HS_HR_GROUP where GP_NAME=(SELECT EMP_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert sub locations
IF (SELECT SUB_LOCATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) IS NOT NULL
BEGIN
If Not Exists(select * from HS_HR_SUB_LOCATION where SUB_LOC_NAME=(SELECT SUB_LOCATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_SUB_LOCATION]
           ([SUB_LOC_CODE]
           ,[SUB_LOC_NAME]
		   ,[LOC_CODE]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(SUB_LOC_CODE),'0')+1),6) AS SUB_LOC_CODE FROM HS_HR_SUB_LOCATION)
		   ,(SELECT SUB_LOCATION FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@LOCATION_CODE
		   ,NULL)
End
END

DECLARE @SUB_LOCATION_CODE VARCHAR(6) 
SET @SUB_LOCATION_CODE = (select SUB_LOC_CODE from HS_HR_SUB_LOCATION where SUB_LOC_NAME=(SELECT EMP_GROUP FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))


-- get Staff Statutory Classification
DECLARE @EMP_ORDINANCECODE VARCHAR(50) 
DECLARE @EMP_ORDINANCECODE_FLG INT
SET @EMP_ORDINANCECODE = (SELECT STAFFCAT_CLASS FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
If(@EMP_ORDINANCECODE = 'Wages Board')
Begin
	set @EMP_ORDINANCECODE_FLG = 1
End
 else if (@EMP_ORDINANCECODE = 'Shop')
 begin  
 set @EMP_ORDINANCECODE_FLG = 0  
 end 
 else
 set @EMP_ORDINANCECODE_FLG = 0 


INSERT INTO HS_HR_EMPLOYEE
	([EMP_NUMBER],
	[EMP_DISPLAY_NUMBER],
	[EMP_DISPLAY_NAME],
	[EMP_TITLE],
	[EMP_CALLING_NAME] ,
	[EMP_SURNAME],
	[EMP_MAIDEN_NAME],
	[EMP_MIDDLE_INI],
	[EMP_NAMES_BY_INI],
	[EMP_FULLNAME],
	[EMP_OTHER_NAMES],
	[EMP_EPF_NUMBER],
	[EMP_NIC_NO],
	[EMP_NIC_DATE],
	[EMP_BIRTHDAY],
	[EMP_BIRTHPLACE],
	[EMP_GENDER],
	[NAT_CODE],
	[RLG_CODE],
	[EMP_BLOOD_GROUP] ,
	[EMP_MARITAL_STATUS],
	[EMP_MARRIED_DATE] ,
	[EMP_DIVOCE_DATE],
	[SAL_GRD_CODE],
	[CT_CODE],
	[DSG_CODE],
	[CENTRE_CODE] ,
	[EMP_DATE_JOINED],
	[EMP_DATE_JOINED_GROUP],
	[EMP_CONFIRM_FLG],
	[EMP_CONFIRM_DATE],
	[EMP_RESIGN_DATE],
	[EMP_RETIRE_DATE],
	[EMP_WORKHOURS],
	[LOC_CODE],
	[EMP_TYPE],
	[EMP_CONTARCT_START_DATE],
	[EMP_CONTRACT_END_DATE],
	[EMP_CONT_TO_PERM_DATE],
	[EMP_BARCODENO],
	[EMP_PAYROLLNO] ,
	[STAFFCAT_CODE],
	[CAT_CODE],
	[GP_CODE],
	[EMP_ACTIVE_HRM_FLG] ,
	[EMP_ACTIVE_PAYROLL_FLG],
	[EMP_ACTIVE_ATT_FLG] ,
	[HIE_CODE_1] ,
	[HIE_CODE_2],
	[HIE_CODE_3] ,
	[HIE_CODE_4],
	[HIE_CODE_5] ,
	[HIE_CODE_6] ,
	[EMP_TAXONTAX_FLG] ,
	[EMP_TAX_ID_NUMBER],
	[EMP_EPF_ELIGIBLE_FLG],
	[EMP_EPF_EMPLOYEE_AMOUNT],
	[EMP_EPF_EMPLOYER_AMOUNT],
	[EMP_ETF_ELIGIBLE_FLG],
	[EMP_ETF_NUMBER],
	[EMP_ETF_EMPLOYEE_AMOUNT] ,
	[EMP_ETF_DATE],
	[EMP_MSPS_ELIGIBLE_FLG],
	[EMP_MSPS_EMPLOYER_AMOUNT],
	[EMP_MSPS_EMPLOYEE_AMOUNT],
	[EMP_PER_ADDRESS1],
	[EMP_PER_ADDRESS2] ,
	[EMP_PER_ADDRESS3],
	[EMP_PER_CITY],
	[EMP_PER_TELEPHONE],
	[EMP_PER_MOBILE],
	[EMP_PER_FAX],
	[EMP_PER_EMAIL],
	[EMP_PER_COU_CODE],
	[EMP_PER_PROVINCE_CODE],
	[EMP_PER_DISTRICT_CODE],
	[EMP_PER_ELECTORATE_CODE],
	[EMP_TEM_ADDRESS1],
	[EMP_TEM_ADDRESS2],
	[EMP_TEM_ADDRESS3],
	[EMP_TEM_CITY],
	[EMP_TEM_POSTALCODE],
	[EMP_TEM_TELEPHONE],
	[EMP_TEM_MOBILE],
	[EMP_TEM_FAX],
	[EMP_TEM_EMAIL],
	[EMP_TEM_COU_CODE],
	[EMP_TEM_PROVINCE_CODE],
	[EMP_TEM_DISTRICT_CODE],
	[EMP_TEM_ELECTORATE_CODE],
	[EMP_OFFICE_PHONE],
	[EMP_OFFICE_EXTN],
	[EMP_OFFICE_EMAIL],
	[HIE_CODE_7] ,
	[HIE_CODE_8],
	[HIE_CODE_9],
	[SUB_LOC_CODE],
	[EMP_DATE_FOR_CONFIRM],
	[EMP_ORDINANCECODE_FLG],
	[EMP_CONT_TO_PERM_FLG],
	[EMP_PAYTYPE_FLG],
	[EMP_EPF_PAYMENT_TYPE_FLG],
	[EMP_COR_ADDRESS_FLG],
	[EMP_IS_REHIRE_FLG])
	VALUES 
	(@MAX_EMP_NUMBER,
	@EMPLOYEEID,
	@EMPLOYEE_DISPLAY_NAME,
	@EMP_TITLE_CODE,
	(SELECT EMP_CALLING_NAME FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_SURNAME  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_MAIDEN_NAME  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_MIDDLE_INI  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_NAMES_BY_INI  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_FULLNAME  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_OTHER_NAMES  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_EPF_NUMBER  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_NIC_NO  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_NIC_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_BIRTHDAY  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_BIRTHPLACE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@EMP_GENDER_CODE,
	@NAT_CODE,
	@RLG_CODE,
	@EMP_BLOOD_GROUP_CODE,
	@EMP_MARITAL_STATUS_CODE,
	(SELECT EMP_MARRIED_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_DIVOCE_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@SAL_GRD_CODE,
	@CORPORATE_TITLE_CODE,
	@DESIGNATION,
	@COST_CENTRE_CODE,
	(SELECT EMP_DATE_JOINED  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_DATE_JOINED_TO_GROUP  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT  ISNULL(EMP_CONFIRM_FLG,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_CONFIRM_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_RESIGN_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_RETIRE_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_WORKHOURS FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@LOCATION_CODE,
	@EMP_TYPE_CODE,
	(SELECT EMP_CONTRACT_START_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_CONTRACT_END_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_CONT_TO_PERM_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_BARCODENO  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PAYROLLNO  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@RECR_COMPANY_CODE,
	@EMP_CATEGORY_CODE,
	@EMP_GROUP_CODE,
	(SELECT  ISNULL(EMP_ACTIVE_HRM_FLG ,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT  ISNULL(EMP_ACTIVE_PAYROLL_FLG ,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT  ISNULL(EMP_ACTIVE_ATT_FLG ,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@HIE_LEVEL_1,
	@HIE_LEVEL_2,
	@HIE_LEVEL_3,
	@HIE_LEVEL_4,
	@HIE_LEVEL_5,
	@HIE_LEVEL_6,
	(SELECT  ISNULL(EMP_TAXONTAX_FLG ,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TAX_ID_NUMBER  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT  ISNULL(EMP_EPF_ELIGIBLE_FLG ,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_EPF_EMPLOYEE_AMOUNT  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_EPF_EMPLOYER_AMOUNT  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT  ISNULL(EMP_ETF_ELIGIBLE_FLG ,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_ETF_NUMBER  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_ETF_EMPLOYEE_AMOUNT  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_ETF_DATE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT  ISNULL(EMP_MSPS_ELIGIBLE_FLG,0) FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_MSPS_EMPLOYER_AMOUNT  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_MSPS_EMPLOYEE_AMOUNT  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_ADDRESS1 FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_ADDRESS2  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_ADDRESS3  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_CITY  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_TELEPHONE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_MOBILE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_FAX  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_PER_EMAIL  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@EMP_PER_COUNTRY,
	@EMP_PER_PROVINCE,
	@EMP_PER_DISTRICT,
	@EMP_PER_ELECTORATE_CODE,
	(SELECT EMP_TEM_ADDRESS1  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_ADDRESS2  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_ADDRESS3  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_CITY  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_POSTALCODE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_TELEPHONE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_MOBILE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_FAX  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_TEM_EMAIL FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@EMP_TEM_COUNTRY,
	@EMP_TEM_PROVINCE,
	@EMP_TEM_DISTRICT,
	@EMP_TEM_ELECTORATE,
	(SELECT EMP_OFFICE_PHONE  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_OFFICE_EXTN  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	(SELECT EMP_OFFICE_EMAIL  FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@HIE_LEVEL_7,
	@HIE_LEVEL_8,
	@HIE_LEVEL_9,
	@SUB_LOCATION_CODE,
	(SELECT EMP_DATE_FOR_CONFIRM FROM HS_HR_IA_EMPLOYEE_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID),
	@EMP_ORDINANCECODE_FLG,
	0,
	0,
	0,
	0,
	0
	)

     select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
    --select 'False' as status , 'Error' as message
	SELECT  
		'False' as status  
       ,ERROR_MESSAGE() AS message
	   ,ERROR_LINE() As errorline; 
END CATCH  

FETCH NEXT
	FROM @CursorAttribute
	INTO @ROW_NUM
		,@EMPLOYEEID
END
CLOSE @CursorAttribute

DEALLOCATE @CursorAttribute
END
