CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_CHECK_PASSWORD]
@USER_ID varchar(20),
@PASSWORD varchar(150)
AS
BEGIN

select 1 from [QADBV9_L2].[HS_HR_IA_USERS] U where U.[USER_ID] = @USER_ID and U.[PASSWORD] = @PASSWORD

END
GO