CREATE or ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_USER_BY_ID]
@USER_ID varchar(20)
AS
BEGIN

SELECT [USER_ID]
      ,[PASSWORD]
	  ,[NAME]
      ,[USERNAME]
      ,[USER_ISACTIVE]
      ,[CREATE_DATE]
	  ,[USER_TYPE_CODE]
  FROM [QADBV9_L2].[HS_HR_IA_USERS] u where u.[USER_ID] = @USER_ID

END
GO