ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [SHORT_LEAVE_TYPE_CODE] varchar(6);

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [LEAVE_TYPE_NAME] char(18) NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [MIN_HOURS_ALLOWED] float NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [MAX_HOURS_ALLOWED] float NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [MAX_OCCURRENCE] float NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [MAX_CONSECUTIVE_HOURS_ALLOWED] char(18) NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [LEAVE_TIME_PERIOD] smallint NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [MAX_HOURS_PER_MONTH] numeric NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [MAX_HOURS_PER_YEAR] numeric NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [MAX_HOURS_PER_YEAR] numeric NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD
ALTER COLUMN [LEAVE_NEED_APPROVAL] numeric NULL;

