ALTER TABLE HS_HR_IA_STATUTORY_LEAVE_UPLOAD
ALTER COLUMN [LEAVE_TYPE] varchar(6);

ALTER TABLE HS_HR_IA_STATUTORY_LEAVE_UPLOAD
ALTER COLUMN [LEAVE_DESCRIPTION] varchar(100) NULL;

ALTER TABLE HS_HR_IA_STATUTORY_LEAVE_UPLOAD
ALTER COLUMN [FUTURE_LEAVE_TYPE] smallint NULL;

ALTER TABLE HS_HR_IA_STATUTORY_LEAVE_UPLOAD
ALTER COLUMN [LEAVE_APPROVAL] smallint NULL;
