CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_COLUMN_TYPES]
@TEMPLATE_ID varchar(6)
AS
BEGIN
	SELECT COL_DATATYPE FROM HS_HR_IA_TEMPLATE_INFO WHERE TEMPLATE_ID=@TEMPLATE_ID ORDER BY COLUMN_ORDER;
END
GO