CREATE OR ALTER PROCEDURE [UPDATE_STAT_LEAVE_COLUMNS]
AS 
BEGIN
UPDATE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
SET FUTURE_LEAVE_TYPE = CASE
    WHEN LEV_TYPE_CFWD IS NULL THEN 0
    ELSE 1
END;

UPDATE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
SET LEV_HAS_NOTICE_PERIOD = CASE
    WHEN NOTICE_PERIOD IS NULL THEN 0
    ELSE 1
END;
END