UPDATE HS_HR_IA_MODULES SET MODULE_NAME='Attendance' where MODULE_ID=65;

DELETE FROM HS_HR_IA_TEMPLATE_INFO;
DELETE FROM HS_HR_IA_ERRORS
DELETE FROM HS_HR_IA_ERRORS_ABSENCE
DELETE FROM HS_HR_IA_ERRORS_SHIFT
DELETE FROM HS_HR_IA_ERRORS_ROSTER
DELETE FROM HS_HR_IA_TEMPLATES;

ALTER TABLE HS_HR_IA_TEMPLATE_INFO
ADD COLUMN_ORDER INT;

ALTER TABLE HS_HR_IA_TEMPLATE_INFO
ALTER COLUMN TEMPLATE_ID NVARCHAR(6) NOT NULL;

ALTER TABLE HS_HR_IA_TEMPLATE_INFO
ALTER COLUMN COL_DBNAME VARCHAR(100) NOT NULL;

ALTER TABLE HS_HR_IA_TEMPLATE_INFO
ADD CONSTRAINT PK_HS_HR_IA_TEMPLATE_INFO
PRIMARY KEY (TEMPLATE_ID, COL_DBNAME);

UPDATE HS_HR_IA_SUBSECTIONS SET IS_ENABLE=0;
UPDATE HS_HR_IA_SUBSECTIONS SET VIEW_ORDER=NULL;

UPDATE HS_HR_IA_MODULES SET IS_ENABLE=0;
UPDATE HS_HR_IA_MODULES SET IS_ENABLE=1 WHERE MODULE_ID=2;
UPDATE HS_HR_IA_MODULES SET VIEW_ORDER=NULL;