UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='LEV_TYPE_CFWD_YEARLY' WHERE TEMPLATE_ID='temp6' AND COL_DBNAME='MAX_ALLOWED_FORWARD'

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='LEV_TYPE_CFWD_LIMIT' WHERE TEMPLATE_ID='temp6' AND COL_DBNAME='MAX_LIMIT'

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
DROP COLUMN MAX_ALLOWED_FORWARD;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
DROP COLUMN MAX_LIMIT;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD							
ADD LEV_TYPE_CFWD_YEARLY [numeric](18, 2) NULL;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD							
ADD LEV_TYPE_CFWD_LIMIT [numeric](18, 2) NULL;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
ADD LEV_TYPE_CFWD [smallint] NULL;

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='LEV_TYPE_CFWD' WHERE TEMPLATE_ID='temp6' AND COL_DBNAME='FUTURE_LEAVE_TYPE';

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
ADD [LEV_HAS_NOTICE_PERIOD] INT NULL;

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
ADD [LEV_TYPE_MAX_DAYS] [numeric](18, 2) NULL;

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='LEV_TYPE_MAX_DAYS' WHERE TEMPLATE_ID='temp6' AND COL_DBNAME='MAXIMUM_LEA_DAYS_IN_SINGL_INS';

ALTER TABLE HS_HR_IA_STATUTRY_LEAVE_UPLOAD
DROP COLUMN MAXIMUM_LEA_DAYS_IN_SINGL_INS;


ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD                          
ADD TBT_ISCONSEC INT;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD 
ADD TBT_ISCONSEC_ALL [int] NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD 
ADD [TBT_CODE] [varchar](6) NOT NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD 
ADD TBT_ISPREDEFINEDTIMES [smallint] NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD 
ADD TBT_PREDEFINED_ONE [numeric](5, 2) NULL;

ALTER TABLE HS_HR_IA_SHORT_LEAVE_UPLOAD 
ADD TBT_PREDEFINED_TWO [numeric](5, 2) NULL;

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='TBT_ISCONSEC_ALL' WHERE TEMPLATE_ID='temp7' AND COL_DBNAME='CONSIDER_ALL_LEAVE_TYPES'

ALTER TABLE [HS_HR_IA_SHORT_LEAVE_UPLOAD]
DROP COLUMN CONSIDER_ALL_LEAVE_TYPES;

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='TBT_PREDEFINED_ONE' WHERE TEMPLATE_ID='temp7' AND COL_DBNAME='DURATION_PER_SLOT_BEG_OF_SHIFT'

ALTER TABLE [HS_HR_IA_SHORT_LEAVE_UPLOAD]
DROP COLUMN DURATION_PER_SLOT_BEG_OF_SHIFT;

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='TBT_PREDEFINED_TWO' WHERE TEMPLATE_ID='temp7' AND COL_DBNAME='DURATION_PER_SLOT_END_OF_SHIFT'

ALTER TABLE [HS_HR_IA_SHORT_LEAVE_UPLOAD]
DROP COLUMN DURATION_PER_SLOT_END_OF_SHIFT;

UPDATE HS_HR_IA_TEMPLATE_INFO SET COL_DBNAME='TBT_CODE' WHERE TEMPLATE_ID='temp7' AND COL_DBNAME='SHORT_LEAVE_TYPE_CODE';

ALTER TABLE [HS_HR_IA_SHORT_LEAVE_UPLOAD]
DROP COLUMN SHORT_LEAVE_TYPE_CODE;
