DELETE FROM HS_HR_IA_WIZARD_QUESTIONS WHERE SUBSECTION_ID='6'
INSERT INTO [QADBV9_L2].[HS_HR_IA_WIZARD_QUESTIONS] 
VALUES 
('6',1,'Please enter the Leave Types','Text'),
('6',2,'Please enter the Leave Description','Text'),
('6',3,'Is the Leave Type Active?','Yes/No'),
('6',4,'Is Covering Employee Required for this Leave Type?','Yes/No'),
('6',5,'Can Half Days be taken for this Leave Type?','Yes/No'),
('6',6,'Does the End Date get automatically calculated for this Leave Type?','Yes/No'),
('6',7,'Can Holidays be taken as Leave for this Leave Type?','Yes/No'),
('6',8,'Is Lieu Leave applicable for this Leave Type?','Yes/No'),
('6',9,'Is Maternity Leave applicable for this Leave Type?','Yes/No'),
('6',10,'Is No Pay Leave applicable for this Leave Type?','Yes/No'),
('6',11,'Is Quarter Leave applicable for this Leave Type?','Yes/No'),
('6',12,'Should the Leave Balance be shown for this Leave Type?','Yes/No'),
('6',13,'Should the Earned/CF Break Down be displayed for this Leave Type?','Yes/No'),
('6',14,'Can the Leave be taken for an Extended Period for this Leave Type?','Yes/No'),
('6',15,'Can Planning be allowed for this Leave Type?','Yes/No'),
('6',16,'Is an Attachment Required for this Leave Type?','Yes/No'),
('6',17,'Should Additional Fields be displayed for this Leave Type?','Yes/No'),
('6',18,'Can Negative Leave Balance be allowed for this Leave Type?','Yes/No'),
('6',19,'Is Kiosk Allowed for this Leave Type?','Yes/No'),
('6',20,'Should Zero Entitlement be hidden for this Leave Type?','Yes/No'),
('6',21,'Can the Approver be selected for this Leave Type?','Yes/No'),
('6',22,'Should the Leave Reason be shown for this Leave Type?','Yes/No'),
('6',23,'Should this Leave Type be considered in the Dashboard?','Yes/No'),
('6',24,'Should this Leave Type be shown in Offboarding?','Yes/No'),
('6',25,'Should this Leave Type be considered for Time Lost?','Yes/No'),
('6',26,'Is Comment Mandatory for this Leave Type?','Yes/No'),
('6',27,'Is this a Long Leave type?','Yes/No'),
('6',28,'Should this Leave Type be hidden in Self Application?','Yes/No'),
('6',29,'Please enter the Apply Sequence in Dashboard for this Leave Type','Numeric'),
('6',30,'Please enter the Maximum Leave Days allowed in a Single Instance for this Leave Type','Numeric'),
('6',31,'Please enter the Yearly Entitlement in Days for this Leave Type','Numeric'),
('6',32,'Please enter the Minimum Days allowed in a Single Leave Application for this Leave Type','Numeric'),
('6',33,'Please enter the Maximum Days allowed in a Single Leave Application for this Leave Type','Numeric'),
('6',34,'Please enter the Number of Absence Days after which a Medical Certificate is required','Numeric'),
('6',35,'Specify the Leave Types not allowed to be applied together with this Leave Type','Drop down-Text'),
('6',36,'Specify how Future Leave is Utilized for this Leave Type','Drop down-Text'),
('6',37,'Please enter the Utilization Period in Months for this Leave Type','Numeric'),
('6',38,'Please enter the Name of the Future Leave Type if the balance is carried forward','Drop down-Text'),
('6',39,'Please enter the Maximum allowed to carry forward as Future Leave for this Leave Type','Numeric'),
('6',40,'Please enter the Ceiling Limit for Carry Forward of Leave Balance for this Leave Type','Numeric'),
('6',41,'Please enter the Notice Period in days if Notice is required for this Leave Type','Numeric'),
('6',42,'Is this a Time Base Leave Type?','Yes/No'),
('6',43,'Please enter the Leave Approval Process for this Leave Type','Numeric'),
('6',44,'Please enter the Leave Rejection Process for this Leave Type','Text'),
('6',45,'Please enter the Leave Cancellation Process for this Leave Type','Text'),
('6',46,'Please enter the Entitlement Criteria for this Leave Type','Drop down-Text'),
('6',47,'Please enter any Comments for this Leave Type','Text');