CREATE OR ALTER PROCEDURE [UPDATE_SHORT_LEAVE_COLUMNS]
AS 
BEGIN
DECLARE @TBP_CODE INT;
SELECT @TBP_CODE = ISNULL(MAX(TBP_CODE), 0) FROM [HS_HR_LTIMEBASE_PERIOD];

INSERT INTO [HS_HR_IA_LTIMEBASE_PERIOD_UPLD](
	[TBP_CODE],
	[TBT_CODE],
	[TBP_PERIOD])
SELECT @TBP_CODE + ROW_NUMBER() OVER (ORDER BY [ID]), 
TBT_CODE,
LEAVE_TIME_PERIOD
FROM HS_HR_IA_SHORT_LEAVE_UPLOAD
END
GO