DROP TABLE HS_HR_LTIMEBASE_PERIOD_UPLOAD
CREATE TABLE [HS_HR_IA_LTIMEBASE_PERIOD_UPLD](
	[TBP_CODE] [int] NOT NULL,
	[TBT_CODE] [varchar](6) NOT NULL,
	[TBP_PERIOD] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[TBP_CODE] ASC,
	[TBT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]
) ON [PRIMARY]
GO