DELETE FROM [HS_HR_IA_ERRORS_ABSENCE]
DELETE FROM [HS_HR_IA_STATUTRY_LEAVE_UPLOAD]


DROP TABLE [HS_HR_IA_STAT_LEA_DRFT_INFO]

DROP TABLE [HS_HR_IA_STATUTRY_LEAVE_UPLOAD]

CREATE TABLE [HS_HR_IA_STATUTRY_LEAVE_UPLOAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LEAVE_TYPE] [varchar](6) NULL,
	[LEAVE_DESCRIPTION] [varchar](100) NULL,
	[ACTIVE] [int] NULL ,
	[COVERING_EMP_REQ] [int] NULL ,
	[ALLOW_HALF_DAYS] [int] NULL ,
	[AUTO_CAL_END_DATE] [int] NULL ,
	[HOLIDAY_AS_LEAVE] [int] NULL ,
	[LIEU_LEAVE] [int] NULL ,
	[MATERNITY_LEAVE] [int] NULL ,
	[NO_PAY_LEAVE] [int] NULL ,
	[QUARTER_LEAVE] [int] NULL ,
	[SHOW_BALANCE] [int] NULL ,
	[EARNED_CF_BREAK_DOWN] [int] NULL ,
	[EXTENDED_PERIOD] [int] NULL ,
	[ALLOW_PLANNING] [int] NULL ,
	[ATTACHMENT_REQUIRED] [int] NULL ,
	[VIEW_ADDITIONAL_FIELD] [int] NULL ,
	[ALLOW_NEGATIVE] [int] NULL ,
	[KIOSK_ALLOWED] [int] NULL ,
	[HIDE_ZERO_ENTITLEMENT] [int] NULL ,
	[ALLOW_SELECT_APPROVER] [int] NULL ,
	[SHOW_LEAVE_REASON] [int] NULL ,
	[CONSIDER_IN_DASHBOARD] [int] NULL ,
	[SHOW_IN_OFFBOARDING] [int] NULL ,
	[CONSIDER_FOR_TIME_LOST] [int] NULL ,
	[COMMENT_MANDATORY] [int] NULL ,
	[LONG_LEAVE] [int] NULL ,
	[HIDE_IN_SELF_APP] [int] NULL ,
	[APPLY_SEQUENCE_IN_DASH] [int] NULL ,
	[LEV_TYPE_MAX_DAYS] [numeric](18, 2) NULL ,
	[YEARLY_ENTITLEMENT] [numeric](18, 2) NULL ,
	[MINIMUM_DAYS_IN_SNGLE_LEA_APP] [numeric](18, 2) NULL ,
	[MAXIMUM_DAYS_IN_SNGLE_LEA_APP] [numeric](18, 2) NULL ,
	[REQ_MEDICAL_CERTIFICATE] [numeric](18, 2) NULL ,
	[APPLY_TGTHER_WITH_LEA_TYPE] [varchar](50) NULL,
	[FUTURE_LEAVE_UTILIZED_AS] [varchar](50) NULL,
	[UTILIZATION_PERIOD] [numeric](18, 2) NULL ,
	[FUTURE_LEAVE_TYPE_NAME] [varchar](50) NULL,
	[LEV_TYPE_CFWD_YEARLY] [numeric](18, 2) NULL ,
	[LEV_TYPE_CFWD_LIMIT] [numeric](18, 2) NULL ,
	[NOTICE_PERIOD] [numeric](18, 2) NULL ,
	[ENTITLEMENT_CRITERIA] [varchar](100) NULL,
	[COMMENTS] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



CREATE TABLE [QADBV9_L2].[HS_HR_IA_STAT_LEA_DRFT_INFO](
	[USER_ID] [nvarchar](20) NOT NULL,
	[TABLE_RECORD_ID] [int] NOT NULL,
	[IS_DRAFT] [bit] NOT NULL,
	[DATE_TIME] [datetime] NOT NULL,
	[IS_APPROVED] [bit] NULL
) ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_STAT_LEA_DRFT_INFO]  WITH CHECK ADD  CONSTRAINT [fk_hr_hr_ia_stat_lea_drft_stat_lea_upload] FOREIGN KEY([TABLE_RECORD_ID])
REFERENCES [QADBV9_L2].[HS_HR_IA_STATUTRY_LEAVE_UPLOAD] ([ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_STAT_LEA_DRFT_INFO] CHECK CONSTRAINT [fk_hr_hr_ia_stat_lea_drft_stat_lea_upload]
GO

-- Short
DELETE FROM [HS_HR_IA_ERRORS_ABSENCE]
DELETE FROM [HS_HR_IA_SHORT_LEAVE_UPLOAD]


DROP TABLE [HS_HR_IA_SHRT_LEA_DRFT_INFO]

DROP TABLE [HS_HR_IA_SHORT_LEAVE_UPLOAD]

CREATE TABLE [HS_HR_IA_SHORT_LEAVE_UPLOAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TBT_CODE] [varchar](6) NOT NULL,
	[LEAVE_TYPE_NAME] [char](18) NULL,
	[MIN_HOURS_ALLOWED] [numeric](5, 2) NULL ,
	[MAX_HOURS_ALLOWED] [numeric](5, 2) NULL ,
	[MAX_OCCURRENCE] [int] NULL ,
	[MAX_CONSECUTIVE_HOURS_ALLOWED] [char](18) NULL,
	[TBT_ISCONSEC_ALL] [int] NULL ,
	[MAX_NO_OF_LEAVE_PER_DAY] [int] NULL ,
	[LEAVE_TIME_PERIOD] [numeric](5, 2) NULL ,
	[DURATION_BEGIN_SHIFT] [numeric](5, 2) NULL ,
	[DURATION_END_SHIFT] [numeric](5, 2) NULL ,
	[MAX_HOURS_PER_MONTH] [numeric](5, 2) NULL ,
	[MAX_HOURS_PER_YEAR] [numeric](5, 2) NULL ,
	[APPLICABLE_FOR_WEEKLY] [smallint] NULL ,
	[COMMENTS] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
 
 

CREATE TABLE [HS_HR_IA_SHRT_LEA_DRFT_INFO](
	[USER_ID] [nvarchar](20) NOT NULL,
	[TABLE_RECORD_ID] [int] NOT NULL,
	[IS_DRAFT] [bit] NOT NULL,
	[DATE_TIME] [datetime] NOT NULL,
	[IS_APPROVED] [bit] NULL
) ON [PRIMARY]
GO
 
ALTER TABLE [HS_HR_IA_SHRT_LEA_DRFT_INFO]  WITH CHECK ADD  CONSTRAINT [fk_hr_hr_ia_shrt_lea_drft_shrt_lea_upload] FOREIGN KEY([TABLE_RECORD_ID])
REFERENCES [HS_HR_IA_SHORT_LEAVE_UPLOAD] ([ID])
GO
 
ALTER TABLE [HS_HR_IA_SHRT_LEA_DRFT_INFO] CHECK CONSTRAINT [fk_hr_hr_ia_shrt_lea_drft_shrt_lea_upload]
GO