CREATE TABLE [QADBV9_L2].[HS_HR_IA_WIZARD_DRPDWN_OPTNS](
	[SUBSECTION_ID] [nvarchar](6) NOT NULL,
	[MODULE_ID] [int] NOT NULL,
	[QUESTION_NO] [int] NULL,
	[ANSWER_OPTION] [varchar](100) NULL,
) ON [PRIMARY]
GO