CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_CHK_SUBSEC_APPRVD]
@SUBSECTION_NAME VARCHAR(200)
AS
BEGIN
	SELECT TOP 1 APPROVAL_STATUS, VENDOR_APPROVAL_STATUS FROM HS_HR_IA_DASHBOARD_INFO A LEFT JOIN HS_HR_IA_VENDOR_APPROVAL_INFO B ON A.RECORD_ID=B.USER_RECORD_ID LEFT JOIN HS_HR_IA_SUBSECTIONS C ON A.SUBSECTION_ID=C.SUBSECTION_ID WHERE SUBSECTION_NAME=@SUBSECTION_NAME ORDER BY VENDOR_APPROVAL_DATE;
END