CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_UPDATE_SUBSEC_ORDER]
@SUBSECTION_ARRAY HS_HR_IA_DBTYPE_SUBSEC_ORDER READONLY
AS
BEGIN
    UPDATE HS_HR_IA_SUBSECTIONS
    SET VIEW_ORDER = T.VIEW_ORDER, IS_ENABLE=1
    FROM HS_HR_IA_SUBSECTIONS
    INNER JOIN @SUBSECTION_ARRAY AS T ON HS_HR_IA_SUBSECTIONS.SUBSECTION_ID = T.SUBSECTION_ID;
END;