ALTER TABLE HS_HR_IA_MODULES ADD IS_ENABLE bit;

ALTER TABLE HS_HR_IA_SUBSECTIONS ADD IS_ENABLE bit;

UPDATE HS_HR_IA_MODULES SET IS_ENABLE=0 WHERE MODULE_ID=2 OR MODULE_ID=14 OR MODULE_ID=65;

UPDATE HS_HR_IA_SUBSECTIONS SET IS_ENABLE=0 WHERE MODULE_ID=2 OR MODULE_ID=14 OR MODULE_ID=65;

ALTER TABLE HS_HR_IA_MODULES ADD VIEW_ORDER int;

ALTER TABLE HS_HR_IA_SUBSECTIONS ADD VIEW_ORDER int;

CREATE TYPE [QADBV9_L2].[HS_HR_IA_DBTYPE_MODULE_ORDER] AS TABLE
(
    MODULE_ID INT,
    VIEW_ORDER INT
);

CREATE TYPE [QADBV9_L2].[HS_HR_IA_DBTYPE_SUBSEC_ORDER] AS TABLE
(
    SUBSECTION_ID INT,
    VIEW_ORDER INT
);