CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_TEMPLATE_DATA]
@TEMPLATE_ID varchar(6)
AS
BEGIN
	
	SELECT TEMPLATE_ID,MODULE_ID,SUBSECTION_ID,TEMPLATE_NAME,TEMPLATE_DATA,IS_ACTIVE_FLG FROM [QADBV9_L2].[HS_HR_IA_TEMPLATES] WHERE TEMPLATE_ID=@TEMPLATE_ID;

END
GO