CREATE PROCEDURE [QADBV9_L2].[SP_IA_INSERT_INTO_IA_TEMPLATES]
@TEMPLATE_ID varchar(6),
@MODULE_ID INT,
@SUBSECTION_ID	varchar(6),
@TEMPLATE_NAME varchar(200),
@TEMPLATE_DATA varbinary(max),
@IS_ACTIVE_FLG bit
AS
BEGIN

INSERT INTO HS_HR_IA_TEMPLATES (TEMPLATE_ID,MODULE_ID,SUBSECTION_ID,TEMPLATE_NAME,TEMPLATE_DATA,IS_ACTIVE_FLG)
VALUES (@TEMPLATE_ID,@MODULE_ID,@SUBSECTION_ID,@TEMPLATE_NAME,@TEMPLATE_DATA,@IS_ACTIVE_FLG)

END
GO