CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_DB_AND_EXCEL_COLUMNS]
@TEMPLATE_ID varchar(6)
AS
BEGIN
	
	SELECT COL_DBNAME,COL_EXCELNAME FROM [QADBV9_L2].[HS_HR_IA_TEMPLATE_INFO] WHERE TEMPLATE_ID=@TEMPLATE_ID;

END
GO
