Create OR ALTER Procedure [QADBV9_L2].[SP_IA_GET_VALIDATED_DATA]
AS
BEGIN
SET NOCOUNT ON;

select EMP_NUMBER,TEMPLATE_ID,ERROR_DETAILS,COL_NUMBER,COL_NAME,ROW_NUMBER,ERROR_ID from HS_HR_IA_ERRORS

END

