CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_TEMPLATE_ID]
@SUBSECTION_NAME varchar(200)
AS
BEGIN

SET NOCOUNT ON

Select TEMPLATE_ID from HS_HR_IA_TEMPLATES where SUBSECTION_ID=(Select SUBSECTION_ID from HS_HR_IA_SUBSECTIONS where SUBSECTION_NAME=@SUBSECTION_NAME);

END
GO