CREATE TABLE [QADBV9_L2].[HS_HR_IA_SHIFT_INFO_UPLOAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SHIFT_NAME] [varchar](25) NULL,
	[SHIFT_ABR] [varchar](5) NULL,
	[START_TIME] numeric(5,2) NULL,
	[END_TIME] numeric(5,2) NULL,
	[FIRST_HALF_DUR] numeric(5,2) NULL,
	[SECOND_HALF_DUR] numeric(5,2) NULL,
	[FLEXI_SHIFT] int NULL,
	[OFF_SHIFT] int NULL,
	[CONTINUE_SHIFT] int NULL,
	[LATE_COVER] int NULL,
	[BRK_ALLOW_LATE_HRS_CALC] int NULL,
	[ALLOW_DEDCT_OUT_HRS] int NULL,
	[AUTO_MID_NIGHT_FIX] int NULL,
	[NEXT_DAY_SHIFT_OUT_TIME] int NULL,
	[LEAVE_DAYS] numeric(5,2) NULL,
	[OT_ROUND_METHOD] [varchar](200) NULL,
	[OT_ROUNDING] numeric(5,2) NULL,
	[GRACE_PERIOD] numeric(5,2) NULL,
	[BREAK_NAME] [varchar](150) NULL,
	[BREAK_START_TIME] numeric(5,2) NULL,
	[BREAK_DURATION] numeric(5,2) NULL,
	[SHIFT_CODE] [varchar](25) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO