CREATE TABLE [QADBV9_L2].[HS_HR_IA_ROSTER_INFO_UPLOAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROSTER_CODE] [varchar](8) NULL,
	[ROSTER_NAME] [varchar](200) NULL,
	[ROS_IS_ACTIVE] numeric NULL,
	[ROSTER_COMMENT] [varchar](200) NULL,
	[ROS_GRP_NAME] [varchar](50) NULL,
	[ROS_GRP_DESC] [varchar](400) NULL,
	[ROS_HIE] [varchar](70) NULL,
	[ROS_COMP_CALENDER] [varchar](50) NULL,
	[ROS_WRKFLW_TYPE] [varchar](20) NULL,
	[DYN_ROS_SUPERVISOR] [varchar](6) NULL,
	[ROS_GRP_CMNTS] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO