DELETE FROM [HS_HR_IA_SHIFT_INFO_UPLOAD]

ALTER TABLE [HS_HR_IA_SHIFT_INFO_UPLOAD] DROP COLUMN OT_ROUND_METHOD

ALTER TABLE [HS_HR_IA_SHIFT_INFO_UPLOAD] DROP COLUMN OT_ROUNDING

ALTER TABLE [HS_HR_IA_SHIFT_INFO_UPLOAD] DROP COLUMN GRACE_PERIOD
ALTER TABLE [HS_HR_IA_SHIFT_INFO_UPLOAD] DROP COLUMN BREAK_NAME
ALTER TABLE [HS_HR_IA_SHIFT_INFO_UPLOAD] DROP COLUMN BREAK_START_TIME
ALTER TABLE [HS_HR_IA_SHIFT_INFO_UPLOAD] DROP COLUMN BREAK_DURATION


