CREATE TRIGGER trg_insert_into_drpdwn_optns
ON HS_HR_LEAVE_TYPE
AFTER INSERT
AS
BEGIN
  SET NOCOUNT ON;

  INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  SELECT DISTINCT i.LEV_TYPE_CODE, '6', 14, 35
  FROM inserted i;

  INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  SELECT DISTINCT i.LEV_TYPE_CODE, '6', 14, 36
  FROM inserted i;

   INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  SELECT DISTINCT i.LEV_TYPE_CODE, '6', 14, 38
  FROM inserted i;

  INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  SELECT DISTINCT i.LEV_TYPE_CODE, '6', 14, 42
  FROM inserted i;
END;