DELETE FROM HS_HR_IA_WIZARD_DRPDWN_OPTNS

INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION,SUBSECTION_ID, MODULE_ID,QUESTION_NO)
SELECT DISTINCT LEV_TYPE_CODE,'6',14,35 FROM HS_HR_LEAVE_TYPE;

INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION,SUBSECTION_ID, MODULE_ID,QUESTION_NO)
SELECT DISTINCT LEV_TYPE_CODE,'6',14,36 FROM HS_HR_LEAVE_TYPE;

INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION,SUBSECTION_ID, MODULE_ID,QUESTION_NO)
SELECT DISTINCT LEV_TYPE_CODE,'6',14,38 FROM HS_HR_LEAVE_TYPE;

INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION,SUBSECTION_ID, MODULE_ID,QUESTION_NO)
SELECT DISTINCT LEV_TYPE_CODE,'6',14,42 FROM HS_HR_LEAVE_TYPE;