CREATE TABLE [QADBV9_L2].[HS_HR_IA_WIZARD_QUESTIONS](
[SUBSECTION_ID] [nvarchar](6) NOT NULL,
[QUESTION_NO] int NOT NULL,
[QUESTION_STATEMENT][nvarchar](MAX) NULL,
[QUESTION_TYPE][nvarchar](200) NULL,
CONSTRAINT [Pk_HS_HR_IA_WIZARD_QUESTIONS] PRIMARY KEY ([SUBSECTION_ID], [QUESTION_NO])
)
