CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_VALDT_DATA_ABSENCE]
AS
BEGIN
SET NOCOUNT ON;

select CODE,TEMPLATE_ID,ERROR_DETAILS,COL_NUMBER,COL_NAME,ROW_NUMBER,ERROR_ID from HS_HR_IA_ERRORS_ABSENCE

END
GO