CREATE TABLE [QADBV9_L2].[HS_HR_IA_USER_TYPES](
	[USER_TYPE_CODE] [nvarchar](20) NOT NULL,
	[USER_TYPE] [nvarchar](200) NOT NULL,
 CONSTRAINT [USER_TYPE_CODE] PRIMARY KEY CLUSTERED 
(
	[USER_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


