CREATE TABLE [QADBV9_L2].[HS_HR_IA_VENDOR_APPROVAL_INFO](
	[RECORD_ID] [int] IDENTITY(1,1) NOT NULL,
	[VENDOR_APPROVAL_STATUS] [nvarchar](50) NULL,
	[VENDOR_APPROVAL_BY] [nvarchar](20) NULL,
	[VENDOR_APPROVAL_COMMENT] [nvarchar](500) NULL,
	[VENDOR_APPROVAL_DATE] [datetime] NULL,
	[USER_RECORD_ID] int,
PRIMARY KEY CLUSTERED 
(
	[RECORD_ID] ASC
)
) ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_VENDOR_APPROVAL_INFO]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_vendor_approval_detail_user_record_id] FOREIGN KEY([USER_RECORD_ID])
REFERENCES [QADBV9_L2].[HS_HR_IA_DASHBOARD_INFO] ([RECORD_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_VENDOR_APPROVAL_INFO] CHECK CONSTRAINT [fk_hs_hr_ia_vendor_approval_detail_user_record_id]
GO
