CREATE TABLE [QADBV9_L2].[HS_HR_IA_USERS](
	[USER_ID] [nvarchar](20) NOT NULL,
	[PASSWORD] [nvarchar](150) NULL,
	[NAME] [nvarchar](200) NULL,
	[USERNAME] [nvarchar](100) NULL,
	[USER_ISACTIVE] [bit] NULL,
	[CREATE_DATE] [date] NULL,
	[USER_TYPE_CODE] [nvarchar](20) NULL
 CONSTRAINT [pk_HS_HR_IA_USERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_USERS]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_users] FOREIGN KEY([USER_TYPE_CODE])
REFERENCES [QADBV9_L2].[HS_HR_IA_USER_TYPES] ([USER_TYPE_CODE])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_USERS] CHECK CONSTRAINT [fk_hs_hr_ia_users]
GO