CREATE TABLE [QADBV9_L2].[HS_HR_IA_DASHBOARD_INFO](
	[RECORD_ID] [int] NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[MODULE_ID] [int] NOT NULL,
	[SUBSECTION_ID] [nvarchar](6) NOT NULL,
	[APPROVAL_STATUS] [varchar](50) NULL,
	[APPROVAL_BY] [nvarchar](20) NULL,
	[APPROVAL_COMMENT] [varchar](500) NULL,
	[APPROVAL_SIGNATURE] [varchar](200) NULL,
	[APPROVAL_DATE] [datetime] NULL,
	[APPROVAL_DATA] [varbinary](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_DASHBOARD_INFO]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_dashboard_detail_submodule_id] FOREIGN KEY([SUBSECTION_ID])
REFERENCES [QADBV9_L2].[HS_HR_IA_SUBSECTIONS] ([SUBSECTION_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_DASHBOARD_INFO] CHECK CONSTRAINT [fk_hs_hr_ia_dashboard_detail_submodule_id]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_DASHBOARD_INFO]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_dashboard_info] FOREIGN KEY([MODULE_ID])
REFERENCES [QADBV9_L2].[HS_MODULE] ([MODULE_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_DASHBOARD_INFO] CHECK CONSTRAINT [fk_hs_hr_ia_dashboard_info]
GO

