DELETE FROM HS_HR_IA_WIZARD_DRPDWN_OPTNS;

INSERT INTO [HS_HR_IA_WIZARD_DRPDWN_OPTNS]
           ([SUBSECTION_ID]
           ,[MODULE_ID]
           ,[QUESTION_NO]
           ,[ANSWER_OPTION])
     VALUES
           ('6',14,42,'Annual Leave'),
		   ('6',14,42,'Carry Forward'),
		   ('6',14,42,'Casual Leave'),
		   ('6',14,42,'DefaultTimeBase'),
		   ('6',14,42,'Election_Leave_Sri_Lanka'),
		   ('6',14,42,'Maternity_Leave_Sri_Lanka'),
		   ('6',14,42,'Medical_Leave_Sri_Lanka'),
		   ('6',14,42,'Paternity_Leave_Sri_Lanka')
GO

DROP TRIGGER [trg_insert_into_drpdwn_optns]

CREATE TRIGGER [trg_insert_into_drpdwn_optns]
ON [HS_HR_IA_STATUTRY_LEAVE_UPLOAD]
AFTER INSERT
AS
BEGIN
  SET NOCOUNT ON;

  INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  SELECT DISTINCT i.LEAVE_TYPE, '6', 14, 35
  FROM inserted i;

  INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  SELECT DISTINCT i.LEAVE_TYPE, '6', 14, 36
  FROM inserted i;

   INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  SELECT DISTINCT i.LEAVE_TYPE, '6', 14, 38
  FROM inserted i;

  --INSERT INTO HS_HR_IA_WIZARD_DRPDWN_OPTNS (ANSWER_OPTION, SUBSECTION_ID, MODULE_ID, QUESTION_NO)
  --SELECT DISTINCT i.LEV_TYPE_CODE, '6', 14, 42
  --FROM inserted i;
END;
GO

CREATE TRIGGER [trg_delete_from_drpdwn_optns]
ON [HS_HR_IA_STATUTRY_LEAVE_UPLOAD]
AFTER DELETE
AS
BEGIN
  SET NOCOUNT ON;

  DELETE FROM HS_HR_IA_WIZARD_DRPDWN_OPTNS WHERE SUBSECTION_ID = '6' AND QUESTION_NO!=42 AND ANSWER_OPTION IN (SELECT deleted.LEAVE_TYPE FROM deleted);
END;
GO

CREATE OR ALTER TRIGGER [trg_update_drpdwn_optns]
ON [HS_HR_IA_STATUTRY_LEAVE_UPLOAD]
AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON;
	
	UPDATE HS_HR_IA_WIZARD_DRPDWN_OPTNS SET ANSWER_OPTION=i.LEAVE_TYPE FROM HS_HR_IA_WIZARD_DRPDWN_OPTNS AS o
	INNER JOIN deleted AS d ON o.ANSWER_OPTION = d.LEAVE_TYPE
	INNER JOIN inserted AS i ON i.ID = d.ID WHERE o.SUBSECTION_ID='6' AND o.QUESTION_NO!=42 AND o.ANSWER_OPTION IN (SELECT LEAVE_TYPE FROM deleted);

 --   UPDATE HS_HR_IA_WIZARD_DRPDWN_OPTNS SET ANSWER_OPTION=i.LEAVE_TYPE FROM deleted d INNER JOIN inserted i ON d.ID=i.ID WHERE 

	--SELECT * FROM inserted
END;
GO