CREATE OR ALTER PROCEDURE [SP_IA_GET_APRV_STS_MOD_ACTV]
AS
BEGIN
  SELECT A.[SUBSECTION_ID],
		A.[MODULE_ID],
		[APPROVAL_STATUS],
		[VENDOR_APPROVAL_STATUS] 
  FROM [HS_HR_IA_DASHBOARD_INFO] A 
  LEFT JOIN HS_HR_IA_VENDOR_APPROVAL_INFO B ON A.RECORD_ID=B.USER_RECORD_ID
  LEFT JOIN HS_HR_IA_SUBSECTIONS C ON A.SUBSECTION_ID=C.SUBSECTION_ID
  LEFT JOIN HS_HR_IA_MODULES D ON A.MODULE_ID=D.MODULE_ID
END
GO
