CREATE TABLE [HS_HR_IA_PARAMETERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PARA_NAME] [nvarchar](50) NULL,
	[PARA_VALUE] [nvarchar](400) NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO