CREATE TABLE [HS_HR_IA_APPSETTINGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBDOMAIN_NAME] [nvarchar](20) NULL,
	[EHRM_URL] [nvarchar](MAX) NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO