ALTER  PROCEDURE [hrmv9].[SP_IA_CHK_SUBSEC_APPRVD]
@SUBSECTION_NAME VARCHAR(200)
AS
BEGIN

	SELECT APPROVAL_STATUS, VENDOR_APPROVAL_STATUS into #temp1 FROM HS_HR_IA_DASHBOARD_INFO A LEFT JOIN HS_HR_IA_VENDOR_APPROVAL_INFO B ON A.RECORD_ID=B.USER_RECORD_ID LEFT JOIN HS_HR_IA_SUBSECTIONS C ON A.SUBSECTION_ID=C.SUBSECTION_ID WHERE SUBSECTION_NAME=@SUBSECTION_NAME ORDER BY VENDOR_APPROVAL_DATE;
	DECLARE @COUNT INT;
	SELECT @COUNT= COUNT(*) FROM #temp1;
	PRINT(@COUNT)

	IF @COUNT=1
	BEGIN
		SELECT 1 from #temp1 WHERE APPROVAL_STATUS='Approved' AND VENDOR_APPROVAL_STATUS='APPROVED'
	END
	ELSE IF @COUNT>1
	BEGIN
		SELECT TOP 1 1 from #temp1 WHERE APPROVAL_STATUS='Approved' AND VENDOR_APPROVAL_STATUS='APPROVED'
	END
	DROP TABLE #temp1;
END
GO