DELETE FROM [HS_HR_IA_PARAMETERS];
DROP TABLE [HS_HR_IA_PARAMETERS];


CREATE TABLE [hrmv9].[HS_HR_IA_PARAMETERS](
	[PARA_NAME] [nvarchar](50) NOT NULL,
	[PARA_VALUE] [nvarchar](400) NULL,
PRIMARY KEY CLUSTERED 
(
	[PARA_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO [HS_HR_IA_PARAMETERS]
           ([PARA_NAME]
           ,[PARA_VALUE])
     VALUES
           ('PHR_CONFIG_ASSIST_COPYRIGHTS'
           ,'PeoplesHR, 2023')
GO
