CREATE PROCEDURE [QADBV9_L2].[SP_IA_GET_CLIENT_URL]
@SUBDOMAIN_NAME NVARCHAR(MAX)
AS
BEGIN
SELECT CLISYSCON_EHRM_URL FROM HS_CLIENT_SYSTEM_CONFIG WHERE CLISYSCON_SUBDOMAIN_SSHR=@SUBDOMAIN_NAME;
END
GO