CREATE PROCEDURE [QADBV9_L2].[SP_AI_UPLOAD_EMPLOYEE]
AS 
BEGIN
Declare @LASTCODE as VARCHAR(6)  
Declare @LASTEMPCODE as VARCHAR(8)  
BEGIN TRY  

 

-- insert Gender
set @LASTCODE=0     
select @LASTCODE= isnull(MAX(GEN_CODE),'-1') FROM HS_HR_GENDER
INSERT INTO HS_HR_GENDER (GEN_CODE, GEN_NAME, GEN_DESC,DBGROUP_ID)
SELECT  right('0'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_GENDER) )+ @LASTCODE)),1) AS GEN_CODE, EMP_GENDER, EMP_GENDER,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE EMP_GENDER IS NOT NULL AND  ltrim(rtrim(EMP_GENDER))<>'' AND               
upper(EMP_GENDER) NOT IN (SELECT upper(GEN_NAME) FROM HS_HR_GENDER)
GROUP BY EMP_GENDER

 

-- insert title
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(SALU_ID)),0) from HS_HR_SALUTATION 
INSERT INTO HS_HR_SALUTATION (SALU_CODE, SALU_ID, SALU_NAME,SALU_GENDER,SALU_GENDER_VALIDATION_FLG,DBGROUP_ID)
SELECT EMP_TITLE, right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by emp_title) )+ @LASTCODE)),6) AS SALU_ID, EMP_TITLE, '0','0',null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE EMP_TITLE IS NOT NULL AND  ltrim(rtrim(EMP_TITLE))<>'' AND               
upper(emp_title) NOT IN (SELECT upper(SALU_CODE) FROM HS_HR_SALUTATION)
GROUP BY EMP_TITLE

 

-- insert NATIONALITY
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(NAT_CODE)),0) from HS_HR_NATIONALITY 
INSERT INTO HS_HR_NATIONALITY (NAT_CODE, NAT_NAME, DBGROUP_ID,NAT_CODE_REF)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by NATIONALITY) )+ @LASTCODE)),6) AS NAT_CODE, NATIONALITY,null,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE NATIONALITY IS NOT NULL AND  ltrim(rtrim(NATIONALITY))<>'' AND               
upper(NATIONALITY) NOT IN (SELECT upper(NAT_NAME) FROM HS_HR_NATIONALITY)
GROUP BY NATIONALITY

 

-- insert Religion
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(RLG_CODE)),0) from HS_HR_RELIGION 
INSERT INTO HS_HR_RELIGION (RLG_CODE, RLG_NAME, DBGROUP_ID,RLG_CODE_REF)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by RELIGION) )+ @LASTCODE)),6) AS RLG_CODE, RELIGION,null,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE RELIGION IS NOT NULL AND  ltrim(rtrim(RELIGION))<>'' AND               
upper(RELIGION) NOT IN (SELECT upper(RLG_NAME) FROM HS_HR_RELIGION)
GROUP BY RELIGION

 

-- insert  Blood group
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(BLGRP_ID)),0) from HS_HR_BLOOD_GROUP 
INSERT INTO HS_HR_BLOOD_GROUP (BLGRP_CODE, BLGRP_ID, BLGRP_NAME,DBGROUP_ID)
SELECT EMP_BLOOD_GROUP,right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_BLOOD_GROUP) )+ @LASTCODE)),6) AS BLGRP_ID, EMP_BLOOD_GROUP,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE EMP_BLOOD_GROUP IS NOT NULL AND  ltrim(rtrim(EMP_BLOOD_GROUP))<>'' AND               
upper(EMP_BLOOD_GROUP) NOT IN (SELECT upper(BLGRP_CODE) FROM HS_HR_BLOOD_GROUP)
GROUP BY EMP_BLOOD_GROUP

 

-- insert marital status
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(MARST_ID)),0) from HS_HR_MARITAL_STATUS 
INSERT INTO HS_HR_MARITAL_STATUS (MARST_CODE, MARST_ID, MARST_NAME,DBGROUP_ID)
SELECT EMP_MARITAL_STATUS,right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_MARITAL_STATUS) )+ @LASTCODE)),6) AS MARST_ID, EMP_MARITAL_STATUS,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE EMP_MARITAL_STATUS IS NOT NULL AND  ltrim(rtrim(EMP_MARITAL_STATUS))<>'' AND               
upper(EMP_MARITAL_STATUS) NOT IN (SELECT upper(MARST_CODE) FROM HS_HR_MARITAL_STATUS)
GROUP BY EMP_MARITAL_STATUS

 

-- insert country
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(COU_CODE)),0) from HS_HR_COUNTRY 
INSERT INTO HS_HR_COUNTRY (COU_CODE, COU_NAME, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_PER_COUNTRY) )+ @LASTCODE)),6) AS COU_CODE, EMP_PER_COUNTRY,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE EMP_PER_COUNTRY IS NOT NULL AND  ltrim(rtrim(EMP_PER_COUNTRY))<>'' AND               
upper(EMP_PER_COUNTRY) NOT IN (SELECT upper(COU_NAME) FROM HS_HR_COUNTRY)
GROUP BY EMP_PER_COUNTRY

 

set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(COU_CODE)),0) from HS_HR_COUNTRY 
INSERT INTO HS_HR_COUNTRY (COU_CODE, COU_NAME, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_TEM_COUNTRY) )+ @LASTCODE)),6) AS COU_CODE, EMP_TEM_COUNTRY,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD
WHERE EMP_TEM_COUNTRY IS NOT NULL AND  ltrim(rtrim(EMP_TEM_COUNTRY))<>'' AND               
upper(EMP_TEM_COUNTRY) NOT IN (SELECT upper(COU_NAME) FROM HS_HR_COUNTRY)
GROUP BY EMP_TEM_COUNTRY

 

-- insert province
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(PROVINCE_CODE)),0) from HS_HR_PROVINCE 
INSERT INTO HS_HR_PROVINCE (PROVINCE_CODE, PROVINCE_NAME,COU_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_PER_PROVINCE) )+ @LASTCODE)),6) AS PROVINCE_CODE, EMP_PER_PROVINCE,C.COU_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COUNTRY C ON C.COU_NAME=A.EMP_PER_COUNTRY
WHERE EMP_PER_PROVINCE IS NOT NULL AND  ltrim(rtrim(EMP_PER_PROVINCE))<>'' AND               
upper(EMP_PER_PROVINCE) NOT IN (SELECT upper(PROVINCE_NAME) FROM HS_HR_PROVINCE E where E.COU_CODE=C.COU_CODE)
GROUP BY EMP_PER_PROVINCE,COU_CODE

 

set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(PROVINCE_CODE)),0) from HS_HR_PROVINCE 
INSERT INTO HS_HR_PROVINCE (PROVINCE_CODE, PROVINCE_NAME,COU_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_TEM_PROVINCE) )+ @LASTCODE)),6) AS PROVINCE_CODE, EMP_TEM_PROVINCE,C.COU_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COUNTRY C ON C.COU_NAME=A.EMP_TEM_COUNTRY
WHERE EMP_TEM_PROVINCE IS NOT NULL AND  ltrim(rtrim(EMP_TEM_PROVINCE))<>'' AND               
upper(EMP_TEM_PROVINCE) NOT IN (SELECT upper(PROVINCE_NAME) FROM HS_HR_PROVINCE E where E.COU_CODE=C.COU_CODE)
GROUP BY EMP_TEM_PROVINCE,COU_CODE

 

 

-- insert distric
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(DISTRICT_CODE)),0) from HS_HR_DISTRICT 
INSERT INTO HS_HR_DISTRICT (DISTRICT_CODE,DISTRICT_NAME,PROVINCE_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_PER_DISTRICT) )+ @LASTCODE)),6) AS DISTRICT_CODE, EMP_PER_DISTRICT,P.PROVINCE_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_PROVINCE P ON P.PROVINCE_NAME=A.EMP_PER_PROVINCE
WHERE EMP_PER_DISTRICT IS NOT NULL AND  ltrim(rtrim(EMP_PER_DISTRICT))<>'' AND               
upper(EMP_PER_DISTRICT) NOT IN (SELECT upper(DISTRICT_NAME) FROM HS_HR_DISTRICT E where E.PROVINCE_CODE=P.PROVINCE_CODE) 
GROUP BY EMP_PER_DISTRICT,PROVINCE_CODE

 

set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(DISTRICT_CODE)),0) from HS_HR_DISTRICT 
INSERT INTO HS_HR_DISTRICT (DISTRICT_CODE,DISTRICT_NAME,PROVINCE_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_TEM_DISTRICT) )+ @LASTCODE)),6) AS DISTRICT_CODE, EMP_TEM_DISTRICT,P.PROVINCE_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_PROVINCE P ON P.PROVINCE_NAME=A.EMP_TEM_PROVINCE
WHERE EMP_TEM_DISTRICT IS NOT NULL AND  ltrim(rtrim(EMP_TEM_DISTRICT))<>'' AND               
upper(EMP_TEM_DISTRICT) NOT IN (SELECT upper(DISTRICT_NAME) FROM HS_HR_DISTRICT E where E.PROVINCE_CODE=P.PROVINCE_CODE) 
GROUP BY EMP_TEM_DISTRICT,PROVINCE_CODE

 

-- insert electorate
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(ELECTORATE_CODE)),0) from HS_HR_ELECTORATE 
INSERT INTO HS_HR_ELECTORATE (ELECTORATE_CODE,ELECTORATE_NAME,DISTRICT_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_PER_ELECTORATE_CODE) )+ @LASTCODE)),6) AS ELECTORATE_CODE, EMP_PER_ELECTORATE_CODE,D.DISTRICT_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_DISTRICT D ON D.DISTRICT_NAME=A.EMP_PER_DISTRICT
WHERE EMP_PER_ELECTORATE_CODE IS NOT NULL AND  ltrim(rtrim(EMP_PER_ELECTORATE_CODE))<>'' AND               
upper(EMP_PER_ELECTORATE_CODE) NOT IN (SELECT upper(ELECTORATE_NAME) FROM HS_HR_ELECTORATE E where E.DISTRICT_CODE=D.DISTRICT_CODE) 
GROUP BY EMP_PER_ELECTORATE_CODE,DISTRICT_CODE

 

set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(ELECTORATE_CODE)),0) from HS_HR_ELECTORATE 
INSERT INTO HS_HR_ELECTORATE (ELECTORATE_CODE,ELECTORATE_NAME,DISTRICT_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_TEM_ELECTORATE) )+ @LASTCODE)),6) AS ELECTORATE_CODE, EMP_TEM_ELECTORATE,D.DISTRICT_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_DISTRICT D ON D.DISTRICT_NAME=A.EMP_TEM_DISTRICT
WHERE EMP_TEM_ELECTORATE IS NOT NULL AND  ltrim(rtrim(EMP_TEM_ELECTORATE))<>'' AND               
upper(EMP_TEM_ELECTORATE) NOT IN (SELECT upper(ELECTORATE_NAME) FROM HS_HR_ELECTORATE E where E.DISTRICT_CODE=D.DISTRICT_CODE) 
GROUP BY EMP_TEM_ELECTORATE,DISTRICT_CODE

 

-- insert location
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(LOC_CODE)),0) from HS_HR_LOCATION 
INSERT INTO HS_HR_LOCATION (LOC_CODE,LOC_NAME,COU_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by LOCATION) )+ @LASTCODE)),6) AS LOC_CODE, LOCATION,D.COU_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COUNTRY D ON D.COU_NAME=A.EMP_PER_COUNTRY
WHERE LOCATION IS NOT NULL AND  ltrim(rtrim(LOCATION))<>'' AND               
D.COU_CODE+upper(LOCATION) NOT IN (SELECT D.COU_CODE+upper(LOC_NAME) FROM HS_HR_LOCATION) 
GROUP BY LOCATION,COU_CODE

 

-- insert sub locations
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(SUB_LOC_CODE)),0) from HS_HR_SUB_LOCATION 
INSERT INTO HS_HR_SUB_LOCATION (SUB_LOC_CODE,SUB_LOC_NAME,LOC_CODE, DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by SUB_LOCATION) )+ @LASTCODE)),6) AS SUB_LOC_CODE, SUB_LOCATION,D.LOC_CODE,null
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_LOCATION D ON D.LOC_NAME=A.LOCATION
WHERE SUB_LOCATION IS NOT NULL AND  ltrim(rtrim(SUB_LOCATION))<>'' AND               
D.LOC_CODE+upper(SUB_LOCATION) NOT IN (SELECT D.LOC_CODE+upper(SUB_LOC_NAME) FROM HS_HR_SUB_LOCATION) 
GROUP BY SUB_LOCATION,LOC_CODE

 

 

IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=1)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('1','Group')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=2)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('2','Sector')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=3)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('3','Company')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=4)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('4','Division')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=5)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('5','Department')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=6)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('6','sub Department')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=7)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('7','Unit')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=8)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('8','Sub Unit')
END
IF NOT EXISTS (SELECT * FROM HS_HR_COMPANY_HIERARCHY_DEF WHERE DEF_LEVEL=9)
BEGIN
    INSERT INTO HS_HR_COMPANY_HIERARCHY_DEF VALUES('9','Team')
END

 

-- insert HIE_CODE 1 
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_1) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_1,NULL,1,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
WHERE HIE_LEVEL_1 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_1))<>'' AND               
upper(HIE_LEVEL_1) NOT IN (SELECT upper(HIE_NAME) FROM HS_HR_COMPANY_HIERARCHY WHERE DEF_LEVEL=1) 
GROUP BY HIE_LEVEL_1

 

-- insert HIE_CODE 2 
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_2) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_2,C1.HIE_CODE,2,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
WHERE HIE_LEVEL_2 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_2))<>'' AND               
A.HIE_LEVEL_1+upper(HIE_LEVEL_2)+C1.HIE_CODE NOT IN (SELECT A.HIE_LEVEL_1+upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=2) 
GROUP BY HIE_LEVEL_2,C1.HIE_CODE

 

-- insert HIE_CODE 3 
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_3) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_3,C1.HIE_CODE,3,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_2
WHERE HIE_LEVEL_3 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_3))<>'' AND               
A.HIE_LEVEL_1+A.HIE_LEVEL_2+upper(HIE_LEVEL_3)+C1.HIE_CODE NOT IN (SELECT A.HIE_LEVEL_1+A.HIE_LEVEL_2+upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=3) 
GROUP BY HIE_LEVEL_3,C1.HIE_CODE

 

-- insert HIE_CODE 4
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_4) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_4,C1.HIE_CODE,4,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_3
WHERE HIE_LEVEL_4 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_4))<>'' AND               
A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+upper(HIE_LEVEL_4)+C1.HIE_CODE NOT IN (SELECT A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=4) 
GROUP BY HIE_LEVEL_4,C1.HIE_CODE

 

-- insert HIE_CODE 5
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_5) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_5,C1.HIE_CODE,5,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_4
WHERE HIE_LEVEL_5 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_5))<>'' AND               
A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+upper(HIE_LEVEL_5)+C1.HIE_CODE NOT IN (SELECT A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=5) 
GROUP BY HIE_LEVEL_5,C1.HIE_CODE

 

-- insert HIE_CODE 6
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_6) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_6,C1.HIE_CODE,6,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_5
WHERE HIE_LEVEL_6 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_6))<>'' AND               
upper(HIE_LEVEL_6)+C1.HIE_CODE NOT IN (SELECT upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=6) 
GROUP BY HIE_LEVEL_6,C1.HIE_CODE

 

-- insert HIE_CODE 7
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_7) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_7,C1.HIE_CODE,7,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_6
WHERE HIE_LEVEL_7 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_7))<>'' AND               
A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+A.HIE_LEVEL_5+A.HIE_LEVEL_6+upper(HIE_LEVEL_7)+C1.HIE_CODE NOT IN (SELECT A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+A.HIE_LEVEL_5+A.HIE_LEVEL_6+upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=7) 
GROUP BY HIE_LEVEL_7,C1.HIE_CODE

 

-- insert HIE_CODE 8
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_8) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_8,C1.HIE_CODE,8,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_7
WHERE HIE_LEVEL_8 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_8))<>'' AND               
A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+A.HIE_LEVEL_5+A.HIE_LEVEL_6+A.HIE_LEVEL_7+upper(HIE_LEVEL_8)+C1.HIE_CODE NOT IN (SELECT A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+A.HIE_LEVEL_5+A.HIE_LEVEL_6+A.HIE_LEVEL_7+upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=8) 
GROUP BY HIE_LEVEL_8,C1.HIE_CODE

 

-- insert HIE_CODE 9
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(HIE_CODE)),0) from HS_HR_COMPANY_HIERARCHY 
INSERT INTO HS_HR_COMPANY_HIERARCHY (HIE_CODE,HIE_NAME,HIE_RELATIONSHIP, DEF_LEVEL,LOC_CODE,HIE_ISACTIVE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by HIE_LEVEL_9) )+ @LASTCODE)),6) AS HIE_CODE, HIE_LEVEL_9,C1.HIE_CODE,9,NULL,1
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_8
WHERE HIE_LEVEL_9 IS NOT NULL AND  ltrim(rtrim(HIE_LEVEL_9))<>'' AND               
A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+A.HIE_LEVEL_5+A.HIE_LEVEL_6+A.HIE_LEVEL_7+A.HIE_LEVEL_8+upper(HIE_LEVEL_9)+C1.HIE_CODE NOT IN (SELECT A.HIE_LEVEL_1+A.HIE_LEVEL_2+A.HIE_LEVEL_3+A.HIE_LEVEL_4+A.HIE_LEVEL_5+A.HIE_LEVEL_6+A.HIE_LEVEL_7+A.HIE_LEVEL_8+upper(HIE_NAME)+Y.HIE_CODE FROM HS_HR_COMPANY_HIERARCHY Y WHERE DEF_LEVEL=9) 
GROUP BY HIE_LEVEL_9,C1.HIE_CODE

 

 

-- insert salary grade
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(SAL_GRD_CODE)),0) from HS_PR_SALARY_GRADE 
INSERT INTO HS_PR_SALARY_GRADE (SAL_GRD_CODE,SAL_GRD_NAME,HIE_CODE,DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by SAL_GRD) )+ @LASTCODE)),6) AS SAL_GRD_CODE, SAL_GRD,C1.HIE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
WHERE SAL_GRD IS NOT NULL AND  ltrim(rtrim(SAL_GRD))<>'' AND               
A.HIE_LEVEL_1+upper(SAL_GRD) NOT IN (SELECT A.HIE_LEVEL_1+upper(SAL_GRD_NAME) FROM HS_PR_SALARY_GRADE) 
GROUP BY SAL_GRD,C1.HIE_CODE

 

-- insert corporate title
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(CT_CODE)),0) from HS_HR_CORPORATE_TITLE 
INSERT INTO HS_HR_CORPORATE_TITLE (CT_CODE,CT_NAME,CT_TOPLEV_FLG,CT_HEADS_FLG,CT_HEADS_COUNT,SAL_GRD_CODE,MANAGE_POS,HIE_CODE,DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by CORPORATE_TITLE) )+ @LASTCODE)),6) AS CT_CODE, CORPORATE_TITLE,0,0,0,S.SAL_GRD_CODE,0,C1.HIE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
LEFT JOIN HS_PR_SALARY_GRADE S ON S.SAL_GRD_NAME=A.SAL_GRD AND C1.HIE_CODE=S.HIE_CODE
WHERE CORPORATE_TITLE IS NOT NULL AND  ltrim(rtrim(CORPORATE_TITLE))<>'' AND               
A.HIE_LEVEL_1+A.SAL_GRD+upper(CORPORATE_TITLE) NOT IN (SELECT A.HIE_LEVEL_1+A.SAL_GRD+upper(CT_NAME) FROM HS_HR_CORPORATE_TITLE) 
GROUP BY CORPORATE_TITLE,S.SAL_GRD_CODE,C1.HIE_CODE

 

-- insert designation 
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(DSG_CODE)),0) from HS_HR_DESIGNATION 
INSERT INTO HS_HR_DESIGNATION (DSG_CODE,DSG_NAME,CT_CODE,DSG_SNRMGT_FLG,HIE_CODE,DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by DESIGNATION) )+ @LASTCODE)),6) AS DSG_CODE, DESIGNATION,C.CT_CODE,0,C1.HIE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
LEFT JOIN HS_HR_CORPORATE_TITLE C ON C.CT_NAME=A.CORPORATE_TITLE AND C1.HIE_CODE=C.HIE_CODE
WHERE DESIGNATION IS NOT NULL AND  ltrim(rtrim(DESIGNATION))<>'' AND               
A.HIE_LEVEL_1+A.CORPORATE_TITLE+upper(DESIGNATION) NOT IN (SELECT A.HIE_LEVEL_1+A.CORPORATE_TITLE+upper(DSG_NAME) FROM HS_HR_DESIGNATION) 
GROUP BY DESIGNATION,C.CT_CODE,C1.HIE_CODE

 

 

-- insert cost center
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(CENTRE_CODE)),0) from HS_PR_COST_CENTRE 
INSERT INTO HS_PR_COST_CENTRE (CENTRE_CODE,CENTRE_NAME,CENTRE_DESCRIPTION,CENTRE_DESC,HIE_CODE,DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by COST_CENTRE) )+ @LASTCODE)),6) AS CENTRE_CODE, COST_CENTRE,NULL,NULL,C1.HIE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
WHERE COST_CENTRE IS NOT NULL AND  ltrim(rtrim(COST_CENTRE))<>'' AND               
A.HIE_LEVEL_1+upper(COST_CENTRE) NOT IN (SELECT A.HIE_LEVEL_1+upper(CENTRE_NAME) FROM HS_PR_COST_CENTRE) 
GROUP BY COST_CENTRE,C1.HIE_CODE

 

-- insert employee type
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(EMPT_TYPE_CODE)),0) from HS_HR_EMPTYPE 
INSERT INTO HS_HR_EMPTYPE (EMPT_ISDATELIMITED_FLG,EMPT_TYPEDESCRIPTION,EMPT_TYPE_CODE,DBGROUP_ID)
SELECT 0 ,EMP_TYPE,right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_TYPE) )+ @LASTCODE)),6) AS EMPT_TYPE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
WHERE EMP_TYPE IS NOT NULL AND  ltrim(rtrim(EMP_TYPE))<>'' AND               
upper(EMP_TYPE) NOT IN (SELECT upper(EMPT_TYPEDESCRIPTION) FROM HS_HR_EMPTYPE) 
GROUP BY EMP_TYPE

 

 

-- insert staff category
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(STAFFCAT_CODE)),0) from HS_HR_STAFFCAT 
INSERT INTO HS_HR_STAFFCAT (STAFFCAT_CODE,STAFFCAT_NAME,HIE_CODE,DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by RECR_COMPANY) )+ @LASTCODE)),6) AS STAFFCAT_CODE, RECR_COMPANY,C1.HIE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
WHERE RECR_COMPANY IS NOT NULL AND  ltrim(rtrim(RECR_COMPANY))<>'' AND               
A.HIE_LEVEL_1+upper(RECR_COMPANY) NOT IN (SELECT A.HIE_LEVEL_1+upper(STAFFCAT_NAME) FROM HS_HR_STAFFCAT) 
GROUP BY RECR_COMPANY,C1.HIE_CODE

 

-- insert employee category
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(CAT_CODE)),0) from HS_HR_CATEGORY 
INSERT INTO HS_HR_CATEGORY (CAT_CODE,CAT_NAME,HIE_CODE,DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_CATEGORY) )+ @LASTCODE)),6) AS CAT_CODE, EMP_CATEGORY,C1.HIE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
WHERE EMP_CATEGORY IS NOT NULL AND  ltrim(rtrim(EMP_CATEGORY))<>'' AND               
A.HIE_LEVEL_1+upper(EMP_CATEGORY) NOT IN (SELECT A.HIE_LEVEL_1+upper(CAT_NAME) FROM HS_HR_CATEGORY) 
GROUP BY EMP_CATEGORY,C1.HIE_CODE

 

-- insert employee group
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(GP_CODE)),0) from HS_HR_GROUP 
INSERT INTO HS_HR_GROUP (GP_CODE,GP_NAME,HIE_CODE,DBGROUP_ID)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EMP_GROUP) )+ @LASTCODE)),6) AS GP_CODE, EMP_GROUP,C1.HIE_CODE,NULL
FROM HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1
WHERE EMP_GROUP IS NOT NULL AND  ltrim(rtrim(EMP_GROUP))<>'' AND               
A.HIE_LEVEL_1+upper(EMP_GROUP) NOT IN (SELECT A.HIE_LEVEL_1+upper(GP_NAME) FROM HS_HR_GROUP) 
GROUP BY EMP_GROUP,C1.HIE_CODE

 

-- INSERT main table data
set @LASTEMPCODE=0
select @LASTEMPCODE=  RIGHT('00000000' + CAST(COALESCE(MAX(CAST (EMP_NUMBER as integer)),0)  AS VARCHAR),8) FROM HS_HR_EMPLOYEE
INSERT INTO HS_HR_EMPLOYEE
    ([EMP_NUMBER],
    [EMP_DISPLAY_NUMBER],
    [EMP_DISPLAY_NAME],
    [EMP_TITLE],
    [EMP_CALLING_NAME] ,
    [EMP_SURNAME],
    [EMP_MAIDEN_NAME],
    [EMP_MIDDLE_INI],
    [EMP_NAMES_BY_INI],
    [EMP_FULLNAME],
    [EMP_OTHER_NAMES],
    [EMP_EPF_NUMBER],
    [EMP_NIC_NO],
    [EMP_NIC_DATE],
    [EMP_BIRTHDAY],
    [EMP_BIRTHPLACE],
    [EMP_GENDER],
    [NAT_CODE],
    [RLG_CODE],
    [EMP_BLOOD_GROUP] ,
    [EMP_MARITAL_STATUS],
    [EMP_MARRIED_DATE] ,
    [EMP_DIVOCE_DATE],
    [SAL_GRD_CODE],
    [CT_CODE],
    [DSG_CODE],
    [CENTRE_CODE] ,
    [EMP_DATE_JOINED],
    [EMP_DATE_JOINED_GROUP],
    [EMP_CONFIRM_FLG],
    [EMP_CONFIRM_DATE],
    [EMP_RESIGN_DATE],
    [EMP_RETIRE_DATE],
    [EMP_WORKHOURS],
    [LOC_CODE],
    [EMP_TYPE],
    [EMP_CONTARCT_START_DATE],
    [EMP_CONTRACT_END_DATE],
    [EMP_CONT_TO_PERM_DATE],
    [EMP_BARCODENO],
    [EMP_PAYROLLNO] ,
    [STAFFCAT_CODE],
    [CAT_CODE],
    [GP_CODE],
    [EMP_ACTIVE_HRM_FLG] ,
    [EMP_ACTIVE_PAYROLL_FLG],
    [EMP_ACTIVE_ATT_FLG] ,
    [HIE_CODE_1] ,
    [HIE_CODE_2],
    [HIE_CODE_3] ,
    [HIE_CODE_4],
    [HIE_CODE_5] ,
    [HIE_CODE_6] ,
    [EMP_TAXONTAX_FLG] ,
    [EMP_TAX_ID_NUMBER],
    [EMP_EPF_ELIGIBLE_FLG],
    [EMP_EPF_EMPLOYEE_AMOUNT],
    [EMP_EPF_EMPLOYER_AMOUNT],
    [EMP_ETF_ELIGIBLE_FLG],
    [EMP_ETF_NUMBER],
    [EMP_ETF_EMPLOYEE_AMOUNT] ,
    [EMP_ETF_DATE],
    [EMP_MSPS_ELIGIBLE_FLG],
    [EMP_MSPS_EMPLOYER_AMOUNT],
    [EMP_MSPS_EMPLOYEE_AMOUNT],
    [EMP_PER_ADDRESS1],
    [EMP_PER_ADDRESS2] ,
    [EMP_PER_ADDRESS3],
    [EMP_PER_CITY],
    [EMP_PER_TELEPHONE],
    [EMP_PER_MOBILE],
    [EMP_PER_FAX],
    [EMP_PER_EMAIL],
    [EMP_PER_COU_CODE],
    [EMP_PER_PROVINCE_CODE],
    [EMP_PER_DISTRICT_CODE],
    [EMP_PER_ELECTORATE_CODE],
    [EMP_TEM_ADDRESS1],
    [EMP_TEM_ADDRESS2],
    [EMP_TEM_ADDRESS3],
    [EMP_TEM_CITY],
    [EMP_TEM_POSTALCODE],
    [EMP_TEM_TELEPHONE],
    [EMP_TEM_MOBILE],
    [EMP_TEM_FAX],
    [EMP_TEM_EMAIL],
    [EMP_TEM_COU_CODE],
    [EMP_TEM_PROVINCE_CODE],
    [EMP_TEM_DISTRICT_CODE],
    [EMP_TEM_ELECTORATE_CODE],
    [EMP_OFFICE_PHONE],
    [EMP_OFFICE_EXTN],
    [EMP_OFFICE_EMAIL],
    [HIE_CODE_7] ,
    [HIE_CODE_8],
    [HIE_CODE_9],
    [SUB_LOC_CODE],
    [EMP_DATE_FOR_CONFIRM],
    [EMP_ORDINANCECODE_FLG],
    [EMP_CONT_TO_PERM_FLG],
    [EMP_PAYTYPE_FLG],
    [EMP_EPF_PAYMENT_TYPE_FLG],
    [EMP_COR_ADDRESS_FLG],
    [EMP_IS_REHIRE_FLG])
SELECT right('00000000'+rtrim(ltrim(floor(row_number() over (ORDER by A.EMP_NUMBER) )+ @LASTEMPCODE)),8) AS EMP_NUMBER,A.EMP_NUMBER,
COALESCE((A.EMP_CALLING_NAME),'') + '' +  COALESCE((A.EMP_SURNAME),'') AS EMP_DISPLAY_NAME,
T.SALU_CODE,EMP_CALLING_NAME,EMP_SURNAME,EMP_MAIDEN_NAME,EMP_MIDDLE_INI,EMP_NAMES_BY_INI,EMP_FULLNAME,EMP_OTHER_NAMES,EMP_EPF_NUMBER,EMP_NIC_NO,
EMP_NIC_DATE,EMP_BIRTHDAY,EMP_BIRTHPLACE,G.GEN_CODE,N.NAT_CODE,R.RLG_CODE,B.BLGRP_CODE ,M.MARST_CODE,EMP_MARRIED_DATE,EMP_DIVOCE_DATE,S.SAL_GRD_CODE,C.CT_CODE,D.DSG_CODE,CS.CENTRE_CODE,EMP_DATE_JOINED,EMP_DATE_JOINED_TO_GROUP,ISNULL(EMP_CONFIRM_FLG,0),
EMP_CONFIRM_DATE,EMP_RESIGN_DATE,EMP_RETIRE_DATE,EMP_WORKHOURS,L.LOC_CODE,ET.EMPT_TYPE_CODE, EMP_CONTRACT_START_DATE,EMP_CONTRACT_END_DATE,EMP_CONT_TO_PERM_DATE,
EMP_BARCODENO,EMP_PAYROLLNO,ST.STAFFCAT_CODE,CT.CAT_CODE,GP.GP_CODE,ISNULL(EMP_ACTIVE_HRM_FLG ,0),ISNULL(EMP_ACTIVE_PAYROLL_FLG ,0),ISNULL(EMP_ACTIVE_ATT_FLG ,0),    
C1.HIE_CODE,C2.HIE_CODE,C3.HIE_CODE,C4.HIE_CODE,C5.HIE_CODE,C6.HIE_CODE,ISNULL(EMP_TAXONTAX_FLG ,0),EMP_TAX_ID_NUMBER,ISNULL(EMP_EPF_ELIGIBLE_FLG ,0),EMP_EPF_EMPLOYEE_AMOUNT,EMP_EPF_EMPLOYER_AMOUNT,
ISNULL(EMP_ETF_ELIGIBLE_FLG ,0),EMP_ETF_NUMBER,EMP_ETF_EMPLOYEE_AMOUNT,EMP_ETF_DATE,ISNULL(EMP_MSPS_ELIGIBLE_FLG,0),EMP_MSPS_EMPLOYER_AMOUNT,
EMP_MSPS_EMPLOYEE_AMOUNT,EMP_PER_ADDRESS1,EMP_PER_ADDRESS2,EMP_PER_ADDRESS3,EMP_PER_CITY,EMP_PER_TELEPHONE,EMP_PER_MOBILE,EMP_PER_FAX,EMP_PER_EMAIL,
CP.COU_CODE,PP.PROVINCE_CODE,DP.DISTRICT_CODE,EP.ELECTORATE_CODE,EMP_TEM_ADDRESS1,EMP_TEM_ADDRESS2,EMP_TEM_ADDRESS3,EMP_TEM_CITY,EMP_TEM_POSTALCODE,EMP_TEM_TELEPHONE,EMP_TEM_MOBILE,EMP_TEM_FAX,EMP_TEM_EMAIL,
CTE.COU_CODE,PTE.PROVINCE_CODE,DTE.DISTRICT_CODE,ETE.ELECTORATE_CODE,EMP_OFFICE_PHONE,EMP_OFFICE_EXTN,EMP_OFFICE_EMAIL,C7.HIE_CODE,C8.HIE_CODE,C9.HIE_CODE,SUB.SUB_LOC_CODE,EMP_DATE_FOR_CONFIRM, 
CASE
    WHEN upper(A.STAFFCAT_CLASS)='WAGES BOARD' THEN 0
    WHEN upper(A.STAFFCAT_CLASS)='SHOP & OFFICE' THEN 1
    ELSE 0
END AS EMP_ORDINANCECODE_FLG ,0,0,0,0,0 
FROM  HS_HR_IA_EMPLOYEE_UPLOAD A
LEFT JOIN HS_HR_SALUTATION T ON T.SALU_CODE=A.EMP_TITLE
LEFT JOIN HS_HR_GENDER G ON G.GEN_NAME=A.EMP_GENDER
LEFT JOIN HS_HR_NATIONALITY N ON N.NAT_NAME=A.NATIONALITY
LEFT JOIN HS_HR_RELIGION R ON R.RLG_NAME=A.RELIGION
LEFT JOIN HS_HR_BLOOD_GROUP B ON B.BLGRP_CODE=A.EMP_BLOOD_GROUP
LEFT JOIN HS_HR_MARITAL_STATUS M ON M.MARST_CODE=A.EMP_MARITAL_STATUS
LEFT JOIN HS_PR_SALARY_GRADE S ON S.SAL_GRD_NAME=A.SAL_GRD AND S.HIE_CODE= (SELECT HIE_CODE FROM HS_HR_COMPANY_HIERARCHY WHERE HIE_NAME=A.HIE_LEVEL_1 AND DEF_LEVEL=1)
LEFT JOIN HS_HR_CORPORATE_TITLE C ON C.CT_NAME=A.CORPORATE_TITLE AND C.SAL_GRD_CODE=S.SAL_GRD_CODE AND C.HIE_CODE= (SELECT HIE_CODE FROM HS_HR_COMPANY_HIERARCHY WHERE HIE_NAME=A.HIE_LEVEL_1 AND DEF_LEVEL=1)
LEFT JOIN HS_HR_DESIGNATION D ON D.DSG_NAME=A.DESIGNATION AND D.CT_CODE=C.CT_CODE AND D.HIE_CODE = (SELECT HIE_CODE FROM HS_HR_COMPANY_HIERARCHY WHERE HIE_NAME=A.HIE_LEVEL_1 AND DEF_LEVEL=1)
LEFT JOIN HS_PR_COST_CENTRE CS ON CS.CENTRE_NAME=A.COST_CENTRE AND CS.HIE_CODE= (SELECT HIE_CODE FROM HS_HR_COMPANY_HIERARCHY WHERE HIE_NAME=A.HIE_LEVEL_1 AND DEF_LEVEL=1)
LEFT JOIN HS_HR_LOCATION L ON L.LOC_NAME=A.LOCATION AND L.COU_CODE = (SELECT COU_CODE FROM HS_HR_COUNTRY WHERE COU_NAME=A.EMP_PER_COUNTRY)
LEFT JOIN HS_HR_EMPTYPE ET ON ET.EMPT_TYPEDESCRIPTION=A.EMP_TYPE
LEFT JOIN HS_HR_STAFFCAT ST ON ST.STAFFCAT_NAME=A.RECR_COMPANY AND ST.HIE_CODE=(SELECT HIE_CODE FROM HS_HR_COMPANY_HIERARCHY WHERE HIE_NAME=A.HIE_LEVEL_1 AND DEF_LEVEL=1)
LEFT JOIN HS_HR_CATEGORY CT ON CT.CAT_NAME=A.EMP_CATEGORY AND CT.HIE_CODE=(SELECT HIE_CODE FROM HS_HR_COMPANY_HIERARCHY WHERE HIE_NAME=A.HIE_LEVEL_1 AND DEF_LEVEL=1)
LEFT JOIN HS_HR_GROUP GP ON GP.GP_NAME=A.EMP_GROUP AND GP.HIE_CODE=(SELECT HIE_CODE FROM HS_HR_COMPANY_HIERARCHY WHERE HIE_NAME=A.HIE_LEVEL_1 AND DEF_LEVEL=1)
LEFT JOIN HS_HR_COMPANY_HIERARCHY C1 ON C1.HIE_NAME=A.HIE_LEVEL_1 AND C1.DEF_LEVEL=1
LEFT JOIN HS_HR_COMPANY_HIERARCHY C2 ON C2.HIE_NAME=A.HIE_LEVEL_2 AND C2.DEF_LEVEL=2 AND C2.HIE_RELATIONSHIP=C1.HIE_CODE
LEFT JOIN HS_HR_COMPANY_HIERARCHY C3 ON C3.HIE_NAME=A.HIE_LEVEL_3 AND C3.DEF_LEVEL=3 AND C3.HIE_RELATIONSHIP=C2.HIE_CODE
LEFT JOIN HS_HR_COMPANY_HIERARCHY C4 ON C4.HIE_NAME=A.HIE_LEVEL_4 AND C4.DEF_LEVEL=4 AND C4.HIE_RELATIONSHIP=C3.HIE_CODE
LEFT JOIN HS_HR_COMPANY_HIERARCHY C5 ON C5.HIE_NAME=A.HIE_LEVEL_5 AND C5.DEF_LEVEL=5 AND C5.HIE_RELATIONSHIP=C4.HIE_CODE
LEFT JOIN HS_HR_COMPANY_HIERARCHY C6 ON C6.HIE_NAME=A.HIE_LEVEL_6 AND C6.DEF_LEVEL=6 AND C6.HIE_RELATIONSHIP=C5.HIE_CODE
LEFT JOIN HS_HR_COMPANY_HIERARCHY C7 ON C7.HIE_NAME=A.HIE_LEVEL_7 AND C7.DEF_LEVEL=7 AND C7.HIE_RELATIONSHIP=C6.HIE_CODE
LEFT JOIN HS_HR_COMPANY_HIERARCHY C8 ON C8.HIE_NAME=A.HIE_LEVEL_8 AND C8.DEF_LEVEL=8 AND C8.HIE_RELATIONSHIP=C7.HIE_CODE
LEFT JOIN HS_HR_COMPANY_HIERARCHY C9 ON C9.HIE_NAME=A.HIE_LEVEL_9 AND C9.DEF_LEVEL=9 AND C9.HIE_RELATIONSHIP=C8.HIE_CODE
LEFT JOIN HS_HR_SUB_LOCATION SUB ON SUB.SUB_LOC_NAME=A.SUB_LOCATION AND SUB.LOC_CODE=L.LOC_CODE
LEFT JOIN HS_HR_COUNTRY CP ON CP.COU_NAME=A.EMP_PER_COUNTRY
LEFT JOIN HS_HR_PROVINCE PP ON PP.PROVINCE_NAME=A.EMP_PER_PROVINCE AND PP.COU_CODE=CP.COU_CODE
LEFT JOIN HS_HR_DISTRICT DP ON DP.DISTRICT_NAME=A.EMP_PER_DISTRICT AND DP.PROVINCE_CODE=PP.PROVINCE_CODE
LEFT JOIN HS_HR_ELECTORATE EP ON EP.ELECTORATE_NAME=A.EMP_PER_ELECTORATE_CODE AND EP.DISTRICT_CODE=DP.DISTRICT_CODE
LEFT JOIN HS_HR_COUNTRY CTE ON CTE.COU_NAME=A.EMP_TEM_COUNTRY
LEFT JOIN HS_HR_PROVINCE PTE ON PTE.PROVINCE_NAME=A.EMP_TEM_PROVINCE AND PTE.COU_CODE=CTE.COU_CODE
LEFT JOIN HS_HR_DISTRICT DTE ON DTE.DISTRICT_NAME=A.EMP_TEM_DISTRICT AND DTE.PROVINCE_CODE=PTE.PROVINCE_CODE
LEFT JOIN HS_HR_ELECTORATE ETE ON ETE.ELECTORATE_NAME=A.EMP_TEM_ELECTORATE AND ETE.DISTRICT_CODE=DTE.DISTRICT_CODE

select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
    SELECT  
        'False' as status  
       ,ERROR_MESSAGE() AS message;  
END CATCH  
END
GO