CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_WZRD_QUESTIONS]
@SUBSECTION_NAME nvarchar(150)
AS
BEGIN
SELECT QUESTION_NO, QUESTION_STATEMENT,QUESTION_TYPE FROM HS_HR_IA_WIZARD_QUESTIONS WHERE SUBSECTION_ID=(SELECT SUBSECTION_ID FROM HS_HR_IA_SUBSECTIONS WHERE SUBSECTION_NAME=@SUBSECTION_NAME) ORDER BY QUESTION_NO ASC
END
GO