CREATE OR ALTER PROCEDURE [SP_IA_IS_ALL_SUBSEC_ENABLED]
AS
BEGIN
SELECT A.IS_ENABLE into #temp1 From HS_HR_IA_SUBSECTIONS A LEFT JOIN HS_HR_IA_MODULES B ON A.MODULE_ID=B.MODULE_ID WHERE B.IS_ENABLE=1;

SELECT CASE WHEN EXISTS (SELECT 1 FROM #temp1 WHERE IS_ENABLE !=1) THEN 0 ELSE 1 END AS Result;

DROP TABLE #temp1;
END
GO