INSERT INTO HS_HR_IA_TEMPLATE_INFO (TEMPLATE_ID, COL_DBNAME, COL_EXCELNAME,COL_DATATYPE)
VALUES
	(N'temp1', N'EMP_NUMBER', N'Employee no', N'nvarchar'),
	(N'temp1', N'EMP_TITLE', N'Title', N'nvarchar'),
	(N'temp1', N'EMP_CALLING_NAME', N'Calling name (First Name)', N'nvarchar'),
	(N'temp1', N'EMP_SURNAME', N'Surname', N'nvarchar'),
	(N'temp1', N'EMP_MIDDLE_INI', N'Initials', N'nvarchar'),
	(N'temp1', N'EMP_NAMES_BY_INI', N'Names denoted by initials', N'nvarchar'),
	(N'temp1', N'EMP_FULLNAME', N'Full name', N'nvarchar'),
	(N'temp1', N'EMP_NIC_NO', N'NIC no', N'nvarchar'),
	(N'temp1', N'EMP_BIRTHDAY', N'Date of birth', N'date'),
	(N'temp1', N'EMP_GENDER', N'Gender', N'nvarchar'),
	(N'temp1', N'EMP_MAIDEN_NAME', N'Maiden Name (If Married)', N'nvarchar'),
	(N'temp1', N'EMP_OTHER_NAMES', N'Other names', N'nvarchar'),
	(N'temp1', N'EMP_EPF_NUMBER', N'EPF no', N'nvarchar'),
	(N'temp1', N'EMP_NIC_DATE', N'NIC Date', N'date'),
	(N'temp1', N'EMP_BIRTHPLACE', N'Place of birth', N'nvarchar'),
	(N'temp1', N'NATIONALITY', N'Nationality', N'nvarchar'),
	(N'temp1', N'RELIGION', N'Religion', N'nvarchar'),
	(N'temp1', N'EMP_BLOOD_GROUP', N'Blood group', N'nvarchar'),
	(N'temp1', N'EMP_MARITAL_STATUS', N'Marital status', N'nvarchar'),
	(N'temp1', N'EMP_MARRIED_DATE', N'Date of marriage', N'date'),
	(N'temp1', N'EMP_DIVOCE_DATE', N'Date of divorce', N'date'),
	(N'temp1', N'SAL_GRD', N'Salary grade', N'nvarchar'),
	(N'temp1', N'CORPORATE_TITLE', N'Corporate title', N'nvarchar'),
	(N'temp1', N'DESIGNATION', N'Designation', N'nvarchar'),
	(N'temp1', N'COST_CENTRE', N'Cost Centre', N'nvarchar'),
	(N'temp1', N'EMP_DATE_JOINED', N'Date of join', N'date'),
	(N'temp1', N'EMP_DATE_JOINED_TO_GROUP', N'Date join to the Group', N'date'),
	(N'temp1', N'EMP_TYPE', N'Employment type', N'nvarchar'),
	(N'temp1', N'STAFFCAT_CLASS', N'Staff Statutory Classification', N'nvarchar'),
	(N'temp1', N'EMP_BARCODENO', N'Barcode no', N'nvarchar'),
	(N'temp1', N'EMP_PAYROLLNO', N'Payroll no', N'nvarchar'),
	(N'temp1', N'EMP_ACTIVE_HRM_FLG', N'HR active', N'smallint'),
	(N'temp1', N'EMP_ACTIVE_PAYROLL_FLG', N'Payroll active', N'smallint'),
	(N'temp1', N'EMP_ACTIVE_ATT_FLG', N'Attendance active', N'smallint'),
	(N'temp1', N'EMP_CONFIRM_FLG', N'Confirmation status', N'smallint'),
	(N'temp1', N'EMP_CONFIRM_DATE', N'Confirmed Date', N'date'),
	(N'temp1', N'EMP_DATE_FOR_CONFIRM', N'Date for confirmation', N'date'),
	(N'temp1', N'EMP_RESIGN_DATE', N'Date of resignation', N'date'),
	(N'temp1', N'EMP_RETIRE_DATE', N'Date of retirement', N'date'),
	(N'temp1', N'EMP_WORKHOURS', N'Hours of work per day', N'decimal'),
	(N'temp1', N'LOCATION', N'Location', N'nvarchar'),
	(N'temp1', N'SUB_LOCATION', N'Sub Location', N'nvarchar'),
	(N'temp1', N'EMP_CONTRACT_START_DATE', N'Contract start date', N'date'),
	(N'temp1', N'EMP_CONTRACT_END_DATE', N'Contract end date', N'date'),
	(N'temp1', N'EMP_CONT_TO_PERM_DATE', N'Contract to permanent date', N'date'),
	(N'temp1', N'EMP_CATEGORY', N'Employee Category', N'nvarchar'),
	(N'temp1', N'RECR_COMPANY', N'Recruitment Company', N'nvarchar'),
	(N'temp1', N'EMP_GROUP', N'Employee Group', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_1', N'Hierarchy Level 1 (Group)', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_2', N'Hierarchy Level 2 (Company)', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_3', N'Hierarchy Level 3', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_4', N'Hierarchy Level 4', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_5', N'Hierarchy Level 5', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_6', N'Hierarchy Level 6', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_7', N'Hierarchy Level 7', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_8', N'Hierarchy Level 8', N'nvarchar'),
	(N'temp1', N'HIE_LEVEL_9', N'Hierarchy Level 9', N'nvarchar'),
	(N'temp1', N'EMP_TAXONTAX_FLG', N'Tax on tax', N'smallint'),
	(N'temp1', N'EMP_TAX_ID_NUMBER', N'Tax ID no', N'nvarchar'),
	(N'temp1', N'EMP_EPF_ELIGIBLE_FLG', N'EPF eligible', N'smallint'),
	(N'temp1', N'EMP_EPF_EMPLOYEE_AMOUNT', N'EPF employee amount', N'decimal'),
	(N'temp1', N'EMP_EPF_EMPLOYER_AMOUNT', N'EPF employer amount', N'decimal'),
	(N'temp1', N'EMP_ETF_ELIGIBLE_FLG', N'ETF eligible', N'smallint'),
	(N'temp1', N'EMP_ETF_NUMBER', N'ETF no', N'nvarchar'),
	(N'temp1', N'EMP_ETF_EMPLOYEE_AMOUNT', N'ETF employee amount', N'decimal'),
	(N'temp1', N'EMP_ETF_DATE', N'ETF date', N'date'),
	(N'temp1', N'EMP_MSPS_ELIGIBLE_FLG', N'MSPS eligible', N'smallint'),
	(N'temp1', N'EMP_MSPS_EMPLOYER_AMOUNT', N'MSPS employer amount', N'decimal'),
	(N'temp1', N'EMP_MSPS_EMPLOYEE_AMOUNT', N'MSPS employee amount', N'decimal'),
	(N'temp1', N'EMP_PER_ADDRESS1', N'Permanent address line 1', N'nvarchar'),
	(N'temp1', N'EMP_PER_ADDRESS2', N'Permanent address line 2', N'nvarchar'),
	(N'temp1', N'EMP_PER_ADDRESS3', N'Permanent address line 3', N'nvarchar'),
	(N'temp1', N'EMP_PER_CITY', N'Permanent city', N'nvarchar'),
	(N'temp1', N'EMP_PER_TELEPHONE', N'Permanent telephone no', N'nvarchar'),
	(N'temp1', N'EMP_PER_MOBILE', N'Permanent mobile no', N'nvarchar'),
	(N'temp1', N'EMP_PER_FAX', N'Permanent fax no', N'nvarchar'),
	(N'temp1', N'EMP_PER_EMAIL', N'Permanent email', N'nvarchar'),
	(N'temp1', N'EMP_PER_COUNTRY', N'Permanent country', N'nvarchar'),
	(N'temp1', N'EMP_PER_PROVINCE', N'Permanent province', N'nvarchar'),
	(N'temp1', N'EMP_PER_DISTRICT', N'Permanent district', N'nvarchar'),
	(N'temp1', N'EMP_PER_ELECTORATE_CODE', N'Permanent electorate', N'nvarchar'),
	(N'temp1', N'EMP_TEM_ADDRESS1', N'Temporary address 1', N'nvarchar'),
	(N'temp1', N'EMP_TEM_ADDRESS2', N'Temporary address 2', N'nvarchar'),
	(N'temp1', N'EMP_TEM_ADDRESS3', N'Temporary address 3', N'nvarchar'),
	(N'temp1', N'EMP_OFFICE_PHONE', N'Office phone no', N'nvarchar'),
	(N'temp1', N'EMP_TEM_CITY', N'Temporary city', N'nvarchar'),
	(N'temp1', N'EMP_TEM_POSTALCODE', N'Temporary postal', N'nvarchar'),
	(N'temp1', N'EMP_TEM_TELEPHONE', N'Temporary telephone no', N'nvarchar'),
	(N'temp1', N'EMP_TEM_MOBILE', N'Temporary mobile no', N'nvarchar'),
	(N'temp1', N'EMP_TEM_FAX', N'Temporary fax no', N'nvarchar'),
	(N'temp1', N'EMP_TEM_EMAIL', N'Temporary email', N'nvarchar'),
	(N'temp1', N'EMP_TEM_COUNTRY', N'Temporary country', N'nvarchar'),
	(N'temp1', N'EMP_TEM_PROVINCE', N'Temporary province', N'nvarchar'),
	(N'temp1', N'EMP_TEM_DISTRICT', N'Temporary district', N'nvarchar'),
	(N'temp1', N'EMP_TEM_ELECTORATE', N'Temporary electorate', N'nvarchar'),
	(N'temp1', N'EMP_OFFICE_EMAIL', N'Office email', N'nvarchar'),
	(N'temp1', N'EMP_OFFICE_EXTN', N'Office extension', N'nvarchar');