--.......................................................Emergency data............................................................................................................


if  EXISTS (select * from sysobjects where [name] ='SP_AI_EC_UPLOAD')
drop  PROCEDURE SP_AI_EC_UPLOAD
go

CREATE PROCEDURE SP_AI_EC_UPLOAD
AS 
BEGIN
Declare @LASTCODE as VARCHAR(6)  
Declare @LASTCODESEQ as VARCHAR(8)  
BEGIN TRY  

-- insert relationship details
set @LASTCODE=0     
select @LASTCODE= isnull(abs(max(REL_ID)),0) from HS_HR_RELATIONSHIP 
INSERT INTO HS_HR_RELATIONSHIP (REL_ID, REL_CODE, REL_NAME,REL_GENDER_VALIDATE_FLG,REL_WORKADDR_ENABLE_FLG,REL_HOMEADDR_ENABLE_FLG,REL_SCHOOLADDR_ENABLE_FLG)
SELECT right('000000'+rtrim(ltrim(floor(row_number() over (ORDER by EC_RELATIONSHIP) )+ @LASTCODE)),6) AS REL_ID, EC_RELATIONSHIP, EC_RELATIONSHIP,0,0,0,0
FROM HS_HR_IA_EC_UPLOAD
WHERE EC_RELATIONSHIP IS NOT NULL AND  ltrim(rtrim(EC_RELATIONSHIP))<>'' AND               
upper(EC_RELATIONSHIP) NOT IN (SELECT upper(REL_NAME) FROM HS_HR_RELATIONSHIP)
GROUP BY EC_RELATIONSHIP


-- INSERT main table data
INSERT INTO [HS_HR_EMP_EMERGENCY]
           ([EMP_NUMBER]
           ,[EEMERG_CONT_PER_FULLNAME]
           ,[EEMERG_RELATIONSHIP]
           ,[EEMERG_PER_ADDRESS]
           ,[EEMERG_OFFICE_TELEPHONE]
           ,[EEMERG_RES_TELEPHONE]
           ,[EEMERG_MOBILE]
           ,[EEMERG_CONTACT_TYPE_FLG]
           ,[EEMERG_OFFICIAL_ADDRESS]
           ,[EEMERG_EMP_NUMBER]
           ,[EEMERG_SEQNO]
           ,[OPE_ID]
           ,[EEMERG_ORDER]
           ,[EEMERG_TEL_EXT]
           ,[EREL_DEPENDNO])
     select E.EMP_NUMBER, EC.EC_CONT_PER_FULLNAME,R.REL_CODE,EC_PER_ADDRESS,EC_OFFICE_TELEPHONE,EC_RES_TELEPHONE,EC_MOBILE,ISNULL(EC_CONTACT_TYPE_FLG,0),
EC_OFFICIAL_ADDRESS,EE.EMP_NUMBER,ROW_NUMBER() OVER(PARTITION BY E.EMP_NUMBER ORDER BY E.EMP_NUMBER) AS EEMERG_SEQNO,
NULL,EC_RELATIONSHIP_ORDER,EC_TEL_EXT,NULL from HS_HR_IA_EC_UPLOAD EC
LEFT JOIN HS_HR_EMPLOYEE E ON E.EMP_DISPLAY_NUMBER=EC.EMP_NUMBER
LEFT JOIN HS_HR_RELATIONSHIP R ON R.REL_CODE=EC.EC_RELATIONSHIP
LEFT JOIN HS_HR_EMPLOYEE EE ON E.EMP_DISPLAY_NUMBER=EC.EC_EMP_NUMBER

     select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
	SELECT  
		'False' as status  
       ,ERROR_MESSAGE() AS message;  
END CATCH  

END