CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_UPDAT_STAT_LEA_STS]
@INT_ARRAY IntArrayTableType READONLY
AS
BEGIN
	UPDATE HS_HR_IA_STAT_LEA_DRFT_INFO SET IS_APPROVED=1 WHERE TABLE_RECORD_ID IN (SELECT ID FROM @INT_ARRAY);
END;
GO