CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_CHK_DUP_APPLY_SEQ]
@APPLY_SEQUENCE INT,
@USER_ID NVARCHAR(20)
AS
BEGIN
SELECT APPLY_SEQUENCE_IN_DASH, USER_ID into #temp1 FROM HS_HR_IA_STATUTRY_LEAVE_UPLOAD a LEFT JOIN HS_HR_IA_STAT_LEA_DRFT_INFO b on a.ID=b.TABLE_RECORD_ID WHERE b.USER_ID=@USER_ID ORDER BY b.DATE_TIME DESC OFFSET 1 Rows
SELECT 1 FROM #temp1 WHERE APPLY_SEQUENCE_IN_DASH = @APPLY_SEQUENCE
DROP TABLE #temp1
END
GO