CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_DRFT_STS_STAT_LEA]
@USER_ID NVARCHAR(20)
AS
BEGIN
SELECT TOP 1 IS_DRAFT, TABLE_RECORD_ID FROM HS_HR_IA_STAT_LEA_DRFT_INFO WHERE USER_ID=@USER_ID ORDER BY DATE_TIME DESC
END