CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_CHK_NULL_STAT_LEA]
@COLUMN_NO INT,
@ROW_ID INT
AS
BEGIN

DECLARE @COLUMN_NAME NVARCHAR(200);
DECLARE @QUERY NVARCHAR(MAX);

SELECT @COLUMN_NAME = column_name
FROM (
  SELECT DISTINCT column_name,ordinal_position
  FROM information_schema.columns
  WHERE table_name = 'HS_HR_IA_STATUTRY_LEAVE_UPLOAD'
) AS subquery
WHERE ordinal_position = @COLUMN_NO;


SET @QUERY='SELECT 1
FROM HS_HR_IA_STATUTRY_LEAVE_UPLOAD
WHERE Id = '+CAST(@ROW_ID AS NVARCHAR)+' AND (['+@COLUMN_NAME+']) IS NOT NULL'

EXEC(@QUERY)

END
GO