ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_REM_VLDTN_COUNT]
AS
BEGIN
select [SUBSECTION_ID],
        [SUBSECTION_NAME],
      [MODULE_ID],
      [APPROVAL_STATUS],
      [VENDOR_APPROVAL_STATUS] into #temp1 from (
SELECT a.[SUBSECTION_ID],
        a.[SUBSECTION_NAME],
      a.[MODULE_ID],
      b.[APPROVAL_STATUS],
      c.[VENDOR_APPROVAL_STATUS],
      b.[APPROVAL_DATE],
      ROW_NUMBER() over (partition by a.[SUBSECTION_ID] order by a.[SUBSECTION_ID], b.[APPROVAL_DATE] desc) data_num
  FROM [HS_HR_IA_SUBSECTIONS] a 
  LEFT JOIN [HS_HR_IA_DASHBOARD_INFO] b ON a.SUBSECTION_ID=b.SUBSECTION_ID 
  LEFT JOIN HS_HR_IA_VENDOR_APPROVAL_INFO c ON b.RECORD_ID=c.USER_RECORD_ID
  ) x
  where x.data_num = 1

  Select COUNT(*) from #temp1 WHERE APPROVAL_STATUS='Approved' AND (VENDOR_APPROVAL_STATUS IS NULL)
  drop table #temp1
END
GO