CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_INSRT_INTO_IA_VENDR_INFO]
@VENDOR_NAME NVARCHAR(20),
@VENDOR_APPROVAL_STATUS NVARCHAR(50),
@VENDOR_APPROVAL_COMMENT NVARCHAR(500),
@VENDOR_APPROVAL_DATE DATETIME,
@USER_RECORD_ID INT
AS
BEGIN
IF(NOT EXISTS(SELECT 1 FROM HS_HR_IA_VENDOR_APPROVAL_INFO))
BEGIN
	DBCC CHECKIDENT ('[HS_HR_IA_VENDOR_APPROVAL_INFO]', RESEED, 0);
END;
INSERT INTO HS_HR_IA_VENDOR_APPROVAL_INFO (VENDOR_APPROVAL_BY,VENDOR_APPROVAL_STATUS,VENDOR_APPROVAL_COMMENT,VENDOR_APPROVAL_DATE,USER_RECORD_ID) VALUES(@VENDOR_NAME,@VENDOR_APPROVAL_STATUS,@VENDOR_APPROVAL_COMMENT,@VENDOR_APPROVAL_DATE,@USER_RECORD_ID);

END
GO