CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_DELETE_TABLE_DATA]
    @TABLE_NAME VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @SQL NVARCHAR(MAX);

    SET @SQL = 'DELETE FROM ' + @TABLE_NAME;

    EXEC sp_executesql @SQL;

	DBCC CHECKIDENT (@TABLE_NAME, RESEED, 0);
END
GO