CREATE TABLE [QADBV9_L2].[HS_HR_IA_ERRORS](
	[EMP_NUMBER] [varchar](8) NULL,
	[TEMPLATE_ID] [nvarchar](6) NULL,
	[ERROR_DETAILS] [varchar](2000) NULL,
	[COL_NUMBER] [varchar](1000) NULL,
	[COL_NAME] [varchar](1000) NULL,
	[ROW_NUMBER] [varchar](20) NULL,
	[ERROR_ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [pk_HS_HR_IA_ERRORS] PRIMARY KEY CLUSTERED 
(
	[ERROR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_ERRORS]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_errors] FOREIGN KEY([TEMPLATE_ID])
REFERENCES [QADBV9_L2].[HS_HR_IA_TEMPLATES] ([TEMPLATE_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_ERRORS] CHECK CONSTRAINT [fk_hs_hr_ia_errors]
GO

