CREATE TABLE [QADBV9_L2].[HS_HR_IA_DEPINFO_UPLOAD](
	[EMP_NUMBER] [varchar](8) NULL,
	[EREL_RELATIONFULLNAME] [varchar](100) NULL,
	[EREL_RELATIONSHIP] [varchar](20) NULL,
	[EREL_GENDER] [varchar](20) NULL,
	[EREL_BIRTHDAY] [date] NULL,
	[EREL_TELEPHONE] [varchar](20) NULL,
	[EREL_ENTMEDICALBENIFIT_FLG] [smallint] NULL,
	[EREL_WORK_SAME_COMP_FLG] [smallint] NULL,
	[EREL_EDU_CENTRE] [varchar](100) NULL,
	[EREL_HOUSE_ADDRESS] [varchar](200) NULL,
	[EREL_OFFICE_ADDRESS] [varchar](200) NULL,
	[EREL_PF_RATIO] [decimal](5, 2) NULL,
	[EREL_PF_NOMINEE_FLG] [smallint] NULL,
	[EREL_ENTDEATHDONATION_FLG] [smallint] NULL,
	[EREL_LIVINGORNOT_FLG] [smallint] NULL,
	[EREL_NIC_NUMBER] [varchar](20) NULL,
	[EREL_SPOUSE_TELEPHONE] [varchar](20) NULL,
	[EREL_COMMENTS] [varchar](200) NULL,
	[EREL_IS_MARRIED] [smallint] NULL,
	[EREL_IS_WORKING] [smallint] NULL,
	[EREL_EMP_NUMBER] [varchar](8) NULL
) ON [PRIMARY]
GO