CREATE TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATES](
	[TEMPLATE_ID] [nvarchar](6) NOT NULL,
	[SUBSECTION_ID] [nvarchar](6) NULL,
	[TEMPLATE_NAME] [varchar](200) NULL,
	[MODULE_ID] [int] NULL,
	[TEMPLATE_DATA] [varbinary](max) NULL,
	[IS_ACTIVE_FLG] [bit] NULL,
 CONSTRAINT [pk_HS_HR_IA_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[TEMPLATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_templates] FOREIGN KEY([MODULE_ID])
REFERENCES [QADBV9_L2].[HS_MODULE] ([MODULE_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATES] CHECK CONSTRAINT [fk_hs_hr_ia_templates]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_templates_submodule_id] FOREIGN KEY([SUBSECTION_ID])
REFERENCES [QADBV9_L2].[HS_HR_IA_SUBSECTIONS] ([SUBSECTION_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATES] CHECK CONSTRAINT [fk_hs_hr_ia_templates_submodule_id]
GO


