CREATE TABLE [QADBV9_L2].[HS_HR_IA_RH_UPLOAD](
	[EMP_NUMBER] [varchar](8) NULL,
	[DIRECT_SUPERVISOR_NUMBER] [varchar](8) NULL,
	[COMPANY] [varchar](70) NULL,
	[INDIRECT_SUPERVISOR_NUMBER] [varchar](8) NULL
) ON [PRIMARY]
GO


