CREATE TABLE [QADBV9_L2].[HS_HR_IA_MODULES](
	[MODULE_ID] [nvarchar](6) NOT NULL,
	[MODULE_NAME] [varchar](150) NULL,
 CONSTRAINT [pk_HS_HR_IA_MODULES] PRIMARY KEY CLUSTERED 
(
	[MODULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


