CREATE TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATE_INFO](
	[TEMPLATE_ID] [nvarchar](6) NULL,
	[COL_DBNAME] [varchar](100) NULL,
	[COL_EXCELNAME] [varchar](200) NULL,
	[COL_DATATYPE] [varchar](200) NULL
) ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATE_INFO]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_template_details_template_id] FOREIGN KEY([TEMPLATE_ID])
REFERENCES [QADBV9_L2].[HS_HR_IA_TEMPLATES] ([TEMPLATE_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_TEMPLATE_INFO] CHECK CONSTRAINT [fk_hs_hr_ia_template_details_template_id]
GO


