CREATE TABLE [QADBV9_L2].[HS_HR_IA_SUBSECTIONS](
	[SUBSECTION_ID] [nvarchar](6) NOT NULL,
	[SUBSECTION_NAME] [varchar](150) NULL,
	[MODULE_ID] [int] NULL,
 CONSTRAINT [pk_HS_HR_IA_SUBMODULES] PRIMARY KEY CLUSTERED 
(
	[SUBSECTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_SUBSECTIONS]  WITH CHECK ADD  CONSTRAINT [fk_hs_hr_ia_submodules] FOREIGN KEY([MODULE_ID])
REFERENCES [QADBV9_L2].[HS_MODULE] ([MODULE_ID])
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_SUBSECTIONS] CHECK CONSTRAINT [fk_hs_hr_ia_submodules]
GO


