Create OR ALTER Procedure [QADBV9_L2].[SP_IA_GET_VLDT_DATA_ROSTER]
AS
BEGIN
SET NOCOUNT ON;

select ROSTER_CODE,TEMPLATE_ID,ERROR_DETAILS,COL_NUMBER,COL_NAME,ROW_NUMBER,ERROR_ID from HS_HR_IA_ERRORS_ROSTER

END

