ALTER PROCEDURE [QADBV9_L2].[SP_IA_VLDT_DATA]
@TMPLT_ID NVARCHAR(MAX)
AS
BEGIN
	IF @TMPLT_ID='temp1'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_EMP_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END

	ELSE IF @TMPLT_ID='temp2'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_BANK_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END

	ELSE IF @TMPLT_ID='temp3'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_RH_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END

	ELSE IF @TMPLT_ID='temp4'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_DEPINFO_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END

	ELSE IF @TMPLT_ID='temp5'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_EC_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END
	
	ELSE IF @TMPLT_ID='temp6'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_STATUTRY_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END

	ELSE IF @TMPLT_ID='temp7'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_SHORT_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END
	ELSE IF @TMPLT_ID='temp8'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_SHIFT_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END
	ELSE IF @TMPLT_ID='temp9'
	BEGIN
		EXEC [QADBV9_L2].[SP_IA_VALIDATION_ROSTER_UPLD] @TEMPLATE_ID=@TMPLT_ID
	END
END
GO