CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_ATTN_APPRV_COUNT]
AS
BEGIN
	SELECT
		[RECORD_ID],
		[SUBSECTION_ID],
		[SUBSECTION_NAME],
		[MODULE_ID],
		[IS_ENABLE],
		[VIEW_ORDER],
		[APPROVAL_STATUS],
		[VENDOR_APPROVAL_STATUS] into #temp1 from (
	SELECT
		b.[RECORD_ID],
		a.[SUBSECTION_ID],
		a.[SUBSECTION_NAME],
		a.[MODULE_ID],
		a.[IS_ENABLE],
		a.[VIEW_ORDER],
		b.[APPROVAL_STATUS],
		c.[VENDOR_APPROVAL_STATUS],
		b.[APPROVAL_DATE],
		  ROW_NUMBER() over (partition by a.[SUBSECTION_ID] order by a.[SUBSECTION_ID], b.[APPROVAL_DATE] desc) data_num
	  FROM [HS_HR_IA_SUBSECTIONS] a 
	  LEFT JOIN [HS_HR_IA_DASHBOARD_INFO] b ON a.SUBSECTION_ID=b.SUBSECTION_ID 
	  LEFT JOIN HS_HR_IA_VENDOR_APPROVAL_INFO c ON b.RECORD_ID=c.USER_RECORD_ID
	  ) x
	  WHERE x.data_num = 1

	If ((SELECT COUNT(*) FROM HS_HR_IA_SUBSECTIONS WHERE MODULE_ID=65 AND IS_ENABLE=1)=0)
	BEGIN
		SELECT CAST(0 AS FLOAT);
	END
	ELSE
	BEGIN	
		SELECT (SELECT CAST(COUNT(DISTINCT RECORD_ID) AS FLOAT) 
		FROM #temp1 WHERE MODULE_ID=65 AND APPROVAL_STATUS='APPROVED' AND IS_ENABLE=1 AND(VENDOR_APPROVAL_STATUS='APPROVED' OR VENDOR_APPROVAL_STATUS IS NULL)) / (SELECT COUNT(*) FROM HS_HR_IA_SUBSECTIONS WHERE MODULE_ID=65 AND IS_ENABLE=1)
	END
	DROP TABLE #temp1
END
GO