CREATE TABLE [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_UPLOAD]
(
ID INT IDENTITY PRIMARY KEY NOT NULL,
PREFERRED_USERNAME NVARCHAR(100),
LOGIN_LOGO VARBINARY(MAX),
IS_EMP_NUM_MANUALLY_ENTERED BIT,
LOGIN_LOGO_MOBILE VARBINARY(MAX),
IS_REPORT_NAV_ENABLED BIT,
OTHER_CONFIGURATIONS NVARCHAR(1000)
)
GO