CREATE TABLE [QADBV9_L2].[HS_HR_IA_COMN_CNFG_RADIO_OPTNS]
(
QUESTION_NO INT NOT NULL,
OPTION_LABEL NVARCHAR(MAX),
OPTION_VALUE NVARCHAR(MAX)
)

ALTER TABLE [QADBV9_L2].[HS_HR_IA_COMN_CNFG_RADIO_OPTNS] ADD CONSTRAINT fk_hs_hr_ia_hs_hr_ia_comn_cnfg_radio_optns_comn_confg_qstns
FOREIGN KEY ([QUESTION_NO]) REFERENCES [QADBV9_L2].[HS_HR_IA_COMMON_CNFG_QUESTIONS] ([QUESTION_NO])
