CREATE TABLE [QADBV9_L2].[HS_HR_IA_COMMON_CNFG_QUESTIONS](
[QUESTION_NO] int NOT NULL,
[QUESTION_STATEMENT][nvarchar](MAX) NULL,
[QUESTION_TYPE][nvarchar](200) NULL,
CONSTRAINT [Pk_HS_HR_IA_COMMON_CNFG_QUESTIONS] PRIMARY KEY ([QUESTION_NO])
)