CREATE TABLE [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_DRFT_INFO]
(USER_ID nvarchar(20) NOT NULL,
TABLE_RECORD_ID int NOT NULL,
IS_DRAFT bit NOT NULL,
DATE_TIME Datetime NOT NULL,
)

ALTER TABLE [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_DRFT_INFO]
ADD CONSTRAINT fk_hr_hr_ia_commn_confg_drft_info_commn_confg_upload
FOREIGN KEY ([TABLE_RECORD_ID]) REFERENCES [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_UPLOAD]([ID]);
GO

ALTER TABLE [QADBV9_L2].[HS_HR_IA_COMMN_CONFG_DRFT_INFO] CHECK CONSTRAINT fk_hr_hr_ia_commn_confg_drft_info_commn_confg_upload
GO

