if  EXISTS (select * from sysobjects where [name] ='SP_SHORT_LEAVE_UPLOAD')
drop  PROCEDURE SP_SHORT_LEAVE_UPLOAD
go

CREATE PROCEDURE SP_SHORT_LEAVE_UPLOAD
AS 
BEGIN

DECLARE @SHORTLEAVETYPECODE AS VARCHAR(6)
DECLARE @LEAVETYPENAME AS CHAR(18)
DECLARE @MINHOURSALLOWED AS INT
DECLARE @MAXHOURSALLOWED AS INT
DECLARE @MAXOCCURRENCE AS INT
DECLARE @MAXCONSECUTIVEHOURSALLOWED AS INT
DECLARE @MAXNOOFLEAVEPERDAY AS INT
DECLARE @LEAVETIMEPERIOD AS INT
DECLARE @MAXOURSPERMONTH AS INT
DECLARE @MAXHOURSPERYEAR AS INT
DECLARE @LEAVENEEDAPPROVAL AS INT



DECLARE @CursorAttribute CURSOR SET @CursorAttribute = CURSOR FAST_FORWARD
FOR
SELECT Short_leave_TYPE_CODE,LEAVE_TYPE_NAME,MIN_HOURS_ALLOWED,MAX_HOURS_ALLOWED,MAX_OCCURRENCE,MAX_CONSECUTIVE_HOURS_ALLOWED,MAX_NO_OF_LEAVE_PER_DAY,LEAVE_TIME_PERIOD,MAX_HOURS_PER_MONTH,MAX_HOURS_PER_YEAR,LEAVE_NEED_APPROVAL
FROM HS_HR_IA_SHORT_LEAVE_UPLOAD

OPEN @CursorAttribute
FETCH NEXT
FROM @CursorAttribute
INTO @SHORTLEAVETYPECODE
	,@LEAVETYPENAME
	,@MINHOURSALLOWED
	,@MAXHOURSALLOWED 
	,@MAXOCCURRENCE 
	,@MAXCONSECUTIVEHOURSALLOWED 
	,@MAXNOOFLEAVEPERDAY 
	,@LEAVETIMEPERIOD 
	,@MAXOURSPERMONTH 
	,@MAXHOURSPERYEAR 
	,@LEAVENEEDAPPROVAL

	
WHILE @@FETCH_STATUS = 0
BEGIN
BEGIN TRY  
If Not Exists(select * from HS_HR_LTIMEBASE_TYPE where TBT_CODE = @SHORTLEAVETYPECODE)
Begin
INSERT INTO HS_HR_LTIMEBASE_TYPE 
	(
	TBT_CODE,
	TBT_NAME,
	TBT_MINHOURS,
	TBT_MAXHOURS,
	TBT_MAXOCCURRENCE,
	TBT_MAXCONSECHOURS,
	TBT_MAXOCCURPERDAY,
	TBT_ISPERIOD,
	TBT_MONTHWISEHOURS,
	TBT_YEARLYHOURS,
	TBT_ISAPPNEED
	)

VALUES
	(
	@SHORTLEAVETYPECODE, 
	@LEAVETYPENAME,
	@MINHOURSALLOWED,
	@MAXHOURSALLOWED,
	@MAXOCCURRENCE,
	@MAXCONSECUTIVEHOURSALLOWED,
	@MAXNOOFLEAVEPERDAY,
	@LEAVETIMEPERIOD,
	@MAXOURSPERMONTH,
	@MAXHOURSPERYEAR,
	@LEAVENEEDAPPROVAL
	)
END
    select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
    select 'False' as status , 'Error' as message
END CATCH  

FETCH NEXT
	FROM @CursorAttribute
	INTO  @SHORTLEAVETYPECODE
	,@LEAVETYPENAME
	,@MINHOURSALLOWED
	,@MAXHOURSALLOWED 
	,@MAXOCCURRENCE 
	,@MAXCONSECUTIVEHOURSALLOWED 
	,@MAXNOOFLEAVEPERDAY 
	,@LEAVETIMEPERIOD 
	,@MAXOURSPERMONTH 
	,@MAXHOURSPERYEAR 
	,@LEAVENEEDAPPROVAL

END
CLOSE @CursorAttribute

DEALLOCATE @CursorAttribute
	
END

EXEC SP_SHORT_LEAVE_UPLOAD