if  EXISTS (select * from sysobjects where [name] ='SP_AI_EC_UPLOAD')
drop  PROCEDURE SP_AI_EC_UPLOAD
go

CREATE PROCEDURE SP_AI_EC_UPLOAD
AS 
BEGIN
DECLARE @EMPLOYEEID AS VARCHAR(8)
DECLARE @ROW_NUM NUMERIC(12)
DECLARE @CursorAttribute CURSOR SET @CursorAttribute = CURSOR FAST_FORWARD
FOR
SELECT ROW_NUMBER() OVER (
		ORDER BY (
				SELECT 0
				)
		) AS ROW_NUM
	,EMP_NUMBER
FROM HS_HR_IA_EC_UPLOAD

OPEN @CursorAttribute
FETCH NEXT
FROM @CursorAttribute
INTO @ROW_NUM
	,@EMPLOYEEID
WHILE @@FETCH_STATUS = 0
BEGIN
BEGIN TRY  


--Get Employee Number From HS_HR_EMPLOYEE 
DECLARE @EMP_NUMBER VARCHAR(8) 
 
SET @EMP_NUMBER = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=@EMPLOYEEID) 

--Get Employee no of contact person(If internal only) From HS_HR_EMPLOYEE 
DECLARE @EEMERG_EMP_NUMBER VARCHAR(8) 
 
SET @EEMERG_EMP_NUMBER = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=(SELECT EC_EMP_NUMBER FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)) 

-- insert relationship details
If Not Exists(select * from HS_HR_RELATIONSHIP where REL_NAME=(SELECT EC_RELATIONSHIP FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_RELATIONSHIP]
           ([REL_CODE]
           ,[REL_ID]
           ,[REL_NAME]
		   ,[REL_GENDER_VALIDATE_FLG]
		   ,[REL_WORKADDR_ENABLE_FLG]
		   ,[REL_HOMEADDR_ENABLE_FLG]
		   ,[REL_SCHOOLADDR_ENABLE_FLG])
     VALUES
           ((SELECT EC_RELATIONSHIP FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(REL_ID),'0')+1),6) AS REL_ID FROM HS_HR_RELATIONSHIP)
           ,(SELECT EC_RELATIONSHIP FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,0
		   ,0
		   ,0
		   ,0)
End

DECLARE @EC_RELATIONSHIP_CODE VARCHAR(50) 
SET @EC_RELATIONSHIP_CODE = (select REL_CODE from HS_HR_RELATIONSHIP where REL_NAME=(SELECT EC_RELATIONSHIP FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))


INSERT INTO [HS_HR_EMP_EMERGENCY]
           ([EMP_NUMBER]
           ,[EEMERG_CONT_PER_FULLNAME]
           ,[EEMERG_RELATIONSHIP]
           ,[EEMERG_PER_ADDRESS]
           ,[EEMERG_OFFICE_TELEPHONE]
           ,[EEMERG_RES_TELEPHONE]
           ,[EEMERG_MOBILE]
           ,[EEMERG_CONTACT_TYPE_FLG]
           ,[EEMERG_OFFICIAL_ADDRESS]
           ,[EEMERG_EMP_NUMBER]
           ,[EEMERG_SEQNO]
           ,[OPE_ID]
           ,[EEMERG_ORDER]
           ,[EEMERG_TEL_EXT]
           ,[EREL_DEPENDNO])
     VALUES
           (@EMP_NUMBER
           ,(SELECT EC_CONT_PER_FULLNAME FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,@EC_RELATIONSHIP_CODE
           ,(SELECT EC_PER_ADDRESS FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EC_OFFICE_TELEPHONE FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EC_RES_TELEPHONE FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EC_MOBILE FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT ISNULL(EC_CONTACT_TYPE_FLG,0) FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EC_OFFICIAL_ADDRESS FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,@EEMERG_EMP_NUMBER
           ,(SELECT isnull(MAX(EEMERG_SEQNO),'0')+1 AS EEMERG_SEQNO FROM HS_HR_EMP_EMERGENCY WHERE EMP_NUMBER=@EMP_NUMBER)
           ,NULL
           ,(SELECT EC_RELATIONSHIP_ORDER FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EC_TEL_EXT FROM HS_HR_IA_EC_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,NULL)
    select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
    select 'False' as status , 'Error' as message
END CATCH  

FETCH NEXT
	FROM @CursorAttribute
	INTO @ROW_NUM
		,@EMPLOYEEID
END
CLOSE @CursorAttribute

DEALLOCATE @CursorAttribute
END
