if  EXISTS (select * from sysobjects where [name] ='SP_AI_DEPINFO_UPLOAD')
drop  PROCEDURE SP_AI_DEPINFO_UPLOAD
go

CREATE PROCEDURE SP_AI_DEPINFO_UPLOAD
AS 
BEGIN
DECLARE @EMPLOYEEID AS VARCHAR(8)
DECLARE @ROW_NUM NUMERIC(12)
DECLARE @CursorAttribute CURSOR SET @CursorAttribute = CURSOR FAST_FORWARD
FOR
SELECT ROW_NUMBER() OVER (
		ORDER BY (
				SELECT 0
				)
		) AS ROW_NUM
	,EMP_NUMBER
FROM HS_HR_IA_DEPINFO_UPLOAD

OPEN @CursorAttribute
FETCH NEXT
FROM @CursorAttribute
INTO @ROW_NUM
	,@EMPLOYEEID
WHILE @@FETCH_STATUS = 0
BEGIN
BEGIN TRY  


--Get Employee Number From HS_HR_EMPLOYEE 
DECLARE @EMP_NUMBER VARCHAR(8) 
SET @EMP_NUMBER = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=@EMPLOYEEID) 

--Get Employee no of contact person(If internal only) From HS_HR_EMPLOYEE 
DECLARE @EREL_EMP_NUMBER VARCHAR(8) 
SET @EREL_EMP_NUMBER = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=(SELECT EREL_EMP_NUMBER FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)) 

-- insert gender
If Not Exists(select * from HS_HR_GENDER where GEN_NAME=(SELECT EREL_GENDER FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_GENDER]
           ([GEN_CODE]
           ,[GEN_NAME]
           ,[GEN_DESC]
           ,[DBGROUP_ID])
     VALUES
           ((SELECT isnull(MAX(GEN_CODE),'0')+1 AS GEN_CODE FROM HS_HR_GENDER)
           ,(SELECT EREL_GENDER FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EREL_GENDER FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,NULL)
End
DECLARE @EMP_GENDER_CODE VARCHAR(6) 
SET @EMP_GENDER_CODE = (select GEN_CODE from HS_HR_GENDER where GEN_NAME=(SELECT EREL_GENDER FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))



-- insert relationship details
If Not Exists(select * from HS_HR_RELATIONSHIP where REL_NAME=(SELECT EREL_RELATIONSHIP FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_RELATIONSHIP]
           ([REL_CODE]
           ,[REL_ID]
           ,[REL_NAME]
		   ,[REL_GENDER_VALIDATE_FLG]
		   ,[REL_WORKADDR_ENABLE_FLG]
		   ,[REL_HOMEADDR_ENABLE_FLG]
		   ,[REL_SCHOOLADDR_ENABLE_FLG])
     VALUES
           ((SELECT EREL_RELATIONSHIP FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(REL_ID),'0')+1),6) AS REL_ID FROM HS_HR_RELATIONSHIP)
           ,(SELECT EREL_RELATIONSHIP FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,0
		   ,0
		   ,0
		   ,0)
End

DECLARE @EREL_RELATIONSHIP_CODE VARCHAR(50) 
SET @EREL_RELATIONSHIP_CODE = (select REL_CODE from HS_HR_RELATIONSHIP where REL_NAME=(SELECT EREL_RELATIONSHIP FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))



INSERT INTO [HS_HR_EMP_RELATIONINFO]
           ([EMP_NUMBER]
           ,[EREL_RELATIONFULLNAME]
           ,[EREL_DEPENDNO]
           ,[EREL_RELATIONSHIP]
           ,[EREL_SEX_FLG]
           ,[EREL_BIRTHDAY]
           ,[EREL_TELEPHONE]
           ,[EREL_ENTMEDICALBENIFIT_FLG]
           ,[EREL_WORK_SAME_COMP_FLG]
           ,[EREL_EDU_CENTRE]
           ,[EREL_HOUSE_ADDRESS]
           ,[EREL_OFFICE_ADDRESS]
           ,[EREL_PF_RATIO]
           ,[EREL_PF_NOMINEE_FLG]
           ,[EREL_ENTDEATHDONATION_FLG]
           ,[EREL_LIVINGORNOT_FLG]
           ,[EREL_NIC_NUMBER]
           ,[EREL_SPOUSE_TELEPHONE]
           ,[EREL_COMMENTS]
           ,[EREL_IS_MARRIED]
           ,[EREL_IS_WORKING]
		   ,[EREL_EMP_NUMBER])
     VALUES
           (@EMP_NUMBER
           ,(SELECT EREL_RELATIONFULLNAME FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT isnull(MAX(EREL_DEPENDNO),'0')+1  AS EREL_DEPENDNO FROM HS_HR_EMP_RELATIONINFO WHERE EMP_NUMBER=@EMPLOYEEID)
           ,@EREL_RELATIONSHIP_CODE
           ,@EMP_GENDER_CODE
           ,(SELECT EREL_BIRTHDAY FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT EREL_TELEPHONE FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_ENTMEDICALBENIFIT_FLG,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_WORK_SAME_COMP_FLG,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  EREL_EDU_CENTRE FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  EREL_HOUSE_ADDRESS FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  EREL_OFFICE_ADDRESS FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_PF_RATIO,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_PF_NOMINEE_FLG,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_ENTDEATHDONATION_FLG,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_LIVINGORNOT_FLG,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  EREL_NIC_NUMBER FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  EREL_SPOUSE_TELEPHONE FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  EREL_COMMENTS FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_IS_MARRIED,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT  ISNULL(EREL_IS_WORKING,0) FROM HS_HR_IA_DEPINFO_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,@EREL_EMP_NUMBER)
    select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
    select 'False' as status , 'Error' as message
END CATCH  

FETCH NEXT
	FROM @CursorAttribute
	INTO @ROW_NUM
		,@EMPLOYEEID
END
CLOSE @CursorAttribute

DEALLOCATE @CursorAttribute
END