if  EXISTS (select * from sysobjects where [name] ='SP_AI_UPLOAD_REPORTTO')
drop  PROCEDURE SP_AI_UPLOAD_REPORTTO
go

CREATE PROCEDURE SP_AI_UPLOAD_REPORTTO
AS 
BEGIN
DECLARE @EMPLOYEEID AS VARCHAR(8)
DECLARE @ROW_NUM NUMERIC(12)
DECLARE @CursorAttribute CURSOR SET @CursorAttribute = CURSOR FAST_FORWARD
FOR
SELECT ROW_NUMBER() OVER (
		ORDER BY (
				SELECT 0
				)
		) AS ROW_NUM
	,EMP_NUMBER
FROM HS_HR_IA_RH_UPLOAD

OPEN @CursorAttribute
FETCH NEXT
FROM @CursorAttribute
INTO @ROW_NUM
	,@EMPLOYEEID
WHILE @@FETCH_STATUS = 0
BEGIN
BEGIN TRY  

--Get subodinate Employee Number From HS_HR_EMPLOYEE 
DECLARE @EMP_NUMBER VARCHAR(8) 
SET @EMP_NUMBER = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=@EMPLOYEEID)

--Get direct supervisor Employee Number From HS_HR_EMPLOYEE 
DECLARE @SUP_NUMBER VARCHAR(8) 
SET @SUP_NUMBER = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=(SELECT DIRECT_SUPERVISOR_NUMBER FROM HS_HR_IA_RH_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

--Get indirect supervisor Employee Number From HS_HR_EMPLOYEE 
DECLARE @SUP_NUMBER_2 VARCHAR(8) 
SET @SUP_NUMBER_2 = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=(SELECT INDIRECT_SUPERVISOR_NUMBER FROM HS_HR_IA_RH_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert direct supervisor
INSERT INTO [HS_HR_EMP_REPORTTO]
           ([EREP_SUB_EMP_NUMBER]
           ,[EREP_REPORTING_MODE]
           ,[EREP_REPORTING_SEQUENCE]
           ,[EREP_SUP_EMP_NUMBER])
     VALUES
           (@EMP_NUMBER
           ,1
           ,NULL
           ,@SUP_NUMBER)

-- insert indirect supervisor
INSERT INTO [HS_HR_EMP_REPORTTO]
           ([EREP_SUB_EMP_NUMBER]
           ,[EREP_REPORTING_MODE]
           ,[EREP_REPORTING_SEQUENCE]
           ,[EREP_SUP_EMP_NUMBER])
     VALUES
           (@EMP_NUMBER
           ,2
           ,NULL
           ,@SUP_NUMBER_2)
    select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
    select 'False' as status , 'Error' as message
END CATCH  

FETCH NEXT
	FROM @CursorAttribute
	INTO @ROW_NUM
		,@EMPLOYEEID
END
CLOSE @CursorAttribute

DEALLOCATE @CursorAttribute
END