if  EXISTS (select * from sysobjects where [name] ='SP_AI_UPLOAD_EMPBANK')
drop  PROCEDURE SP_AI_UPLOAD_EMPBANK
go

CREATE PROCEDURE SP_AI_UPLOAD_EMPBANK
AS 
BEGIN
DECLARE @EMPLOYEEID AS VARCHAR(8)
DECLARE @ROW_NUM NUMERIC(12)
DECLARE @CursorAttribute CURSOR SET @CursorAttribute = CURSOR FAST_FORWARD
FOR
SELECT ROW_NUMBER() OVER (
		ORDER BY (
				SELECT 0
				)
		) AS ROW_NUM
	,EMP_NUMBER
FROM HS_HR_IA_BANK_UPLOAD

OPEN @CursorAttribute
FETCH NEXT
FROM @CursorAttribute
INTO @ROW_NUM
	,@EMPLOYEEID
WHILE @@FETCH_STATUS = 0
BEGIN
BEGIN TRY  


--Get Employee Number From HS_HR_EMPLOYEE 
DECLARE @EMP_NUMBER VARCHAR(8) 
 
SET @EMP_NUMBER = (SELECT EMP_NUMBER FROM HS_HR_EMPLOYEE WHERE EMP_DISPLAY_NUMBER=@EMPLOYEEID); 

-- insert bank details
If Not Exists(select * from HS_HR_BANK where BANK_CODE=(SELECT BANK_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_BANK]
           ([BANK_CODE]
           ,[BANK_NAME]
           ,[BANK_AUTO_CLR_HOUSE_CODE]
           ,[BNK_MAIN])
     VALUES
           ((SELECT BANK_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT BANK_NAME FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT BANK_NAME FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,0)
End

-- insert branch details
If Not Exists(select * from HS_HR_BRANCH where BBRANCH_AUTO_CLR_HOUSE_CODE=(SELECT BRANCH_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) and BANK_CODE=(SELECT BANK_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_BRANCH]
           ([BBRANCH_SLIPTRANSFERS_FLG]
           ,[BBRANCH_AUTO_CLR_HOUSE_CODE]
           ,[BBRANCH_NAME]
           ,[BBRANCH_CODE]
		   ,[BANK_CODE])
     VALUES
           (1
           ,(SELECT BRANCH_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT BRANCH_NAME FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,(SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(BBRANCH_CODE),'0')+1),6) AS BBRANCH_CODE FROM HS_HR_BRANCH)
		   ,(SELECT BANK_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
End
DECLARE @EMPBRANCH_CODE VARCHAR(6) 
SET @EMPBRANCH_CODE = (select BBRANCH_CODE from HS_HR_BRANCH where BBRANCH_AUTO_CLR_HOUSE_CODE=(SELECT BRANCH_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID) 
						and BANK_CODE=(SELECT BANK_CODE FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert account type details
If Not Exists(select * from HS_HR_BANK_ACCOUNT_TYPE where ACCTYPE_NAME=(SELECT ACCTYPE_ID FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_BANK_ACCOUNT_TYPE]
           ([ACCTYPE_ID]
           ,[ACCTYPE_NAME])
     VALUES
           ((SELECT isnull(MAX(ACCTYPE_ID),'0')+1 AS ACCTYPE_ID FROM HS_HR_BANK_ACCOUNT_TYPE)
           ,(SELECT ACCTYPE_ID FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
End
DECLARE @EBANK_ACC_TYPE_FLG INT 
SET @EBANK_ACC_TYPE_FLG = (select ACCTYPE_ID from HS_HR_BANK_ACCOUNT_TYPE where ACCTYPE_NAME=(SELECT ACCTYPE_ID FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

-- insert currency details
If Not Exists(select * from HS_HR_CURRENCY_TYPE where CURRENCY_SYMBOL=(SELECT CURRENCY_SYMBOL FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
Begin
INSERT INTO [HS_HR_CURRENCY_TYPE]
           ([CURRENCY_ID]
           ,[CURRENCY_NAME]
		   ,[CURRENCY_SYMBOL])
     VALUES
           ((SELECT RIGHT('000000'+ CONVERT(VARCHAR,isnull(MAX(CURRENCY_ID),'0')+1),6) AS CURRENCY_ID FROM HS_HR_CURRENCY_TYPE)
           ,(SELECT CURRENCY_SYMBOL FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
		   ,(SELECT CURRENCY_SYMBOL FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))
End
DECLARE @CURRENCY_ID varchar(6) 
SET @CURRENCY_ID = (select CURRENCY_ID from HS_HR_CURRENCY_TYPE where CURRENCY_SYMBOL=(SELECT CURRENCY_SYMBOL FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID))

INSERT INTO [HS_HR_EMP_BANK]
           ([BBRANCH_CODE]
           ,[EMP_NUMBER]
           ,[EBANK_ACC_NO]
           ,[EBANK_ACC_TYPE_FLG]
           ,[EBANK_ORDER]
           ,[EBANK_ACTIVE_FLAG]
           ,[CURRENCY_ID]
           ,[EMP_NAME])
     VALUES
           (@EMPBRANCH_CODE
           ,@EMP_NUMBER
           ,(SELECT EBANK_ACC_NO FROM HS_HR_IA_BANK_UPLOAD WHERE EMP_NUMBER=@EMPLOYEEID)
           ,@EBANK_ACC_TYPE_FLG
           ,1
           ,1
           ,@CURRENCY_ID
           ,(SELECT EMP_FULLNAME FROM HS_HR_EMPLOYEE WHERE EMP_NUMBER=@EMP_NUMBER))
    select 'True' as status , 'Successfully added' as message
END TRY  
BEGIN CATCH  
    select 'False' as status , 'Error' as message
END CATCH  

FETCH NEXT
	FROM @CursorAttribute
	INTO @ROW_NUM
		,@EMPLOYEEID
END
CLOSE @CursorAttribute

DEALLOCATE @CursorAttribute
END