CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_DASHBOARD_DATA_GROUP]
@PAGE_INDEX INT,
@PAGE_SIZE INT,
@SEARCH_TEXT NVARCHAR(MAX),
@ORDER_BY NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;      
    DECLARE @SQL NVARCHAR(MAX);      
    DECLARE @FINAL_QUERY NVARCHAR(MAX);         
    DECLARE @WHERE_CLS NVARCHAR(MAX);  
    DECLARE @ORDER_CLS NVARCHAR(MAX);
	DECLARE @MODIFIED_ORDER_BY NVARCHAR(50);
    DECLARE @S NVARCHAR(MAX);       
    SET @FINAL_QUERY = N'';         
    SET @WHERE_CLS = N'';

	IF(@SEARCH_TEXT <> '')      
    BEGIN       
        SET @WHERE_CLS = @WHERE_CLS + N'AND (MODULE_NAME LIKE ''%' + @SEARCH_TEXT + N'%'' OR SUBSECTION_NAME LIKE ''%' + @SEARCH_TEXT + N'%'' OR APPROVAL_STATUS LIKE ''%' +@SEARCH_TEXT+N'%'' OR APPROVAL_BY LIKE ''%' + @SEARCH_TEXT + N'%'' OR VENDOR_APPROVAL_BY LIKE ''%' + @SEARCH_TEXT + N'%'' OR VENDOR_APPROVAL_STATUS LIKE ''%' + @SEARCH_TEXT + N'%'')';      
    END

	IF(@ORDER_BY <> '')      
    BEGIN
		SELECT @MODIFIED_ORDER_BY = 
			CASE 
				WHEN CHARINDEX('ID', @ORDER_BY) > 0 
				THEN REPLACE(@ORDER_BY, '_ID', '_NAME')
				ELSE @ORDER_BY 
			END 
        SET @ORDER_CLS =  N'ORDER BY ' + @MODIFIED_ORDER_BY
	END

	SET @FINAL_QUERY=N'
	DECLARE @TOTAL_COUNT INT;      
    DECLARE @RECORD_COUNT INT;

	SELECT b.MODULE_ID, c.SUBSECTION_ID,a.RECORD_ID,MODULE_NAME, SUBSECTION_NAME, APPROVAL_STATUS, APPROVAL_BY,APPROVAL_DATE, d.VENDOR_APPROVAL_STATUS, d.VENDOR_APPROVAL_BY INTO #temp1 FROM HS_HR_IA_DASHBOARD_INFO a LEFT JOIN HS_HR_IA_MODULES b ON a.MODULE_ID=b.MODULE_ID LEFT JOIN HS_HR_IA_SUBSECTIONS c ON a.SUBSECTION_ID=c.SUBSECTION_ID LEFT JOIN HS_HR_IA_VENDOR_APPROVAL_INFO d ON a.RECORD_ID=d.USER_RECORD_ID;

	SELECT * INTO #temp2
	FROM (
	 SELECT *
     , ROW_NUMBER() OVER (PARTITION BY SUBSECTION_NAME ORDER BY APPROVAL_DATE DESC) as rn
		FROM #temp1) t WHERE t.rn=1;

	SELECT * INTO #temp3
	FROM #temp2 WHERE 1=1 '+@WHERE_CLS+';

   	SELECT RECORD_ID, MODULE_NAME, SUBSECTION_NAME, APPROVAL_STATUS, APPROVAL_BY,VENDOR_APPROVAL_STATUS, VENDOR_APPROVAL_BY into #temp4
    FROM (
        SELECT *,
            ROW_NUMBER() OVER ( ' +@ORDER_CLS+ ' ) RecordID
        FROM #temp3 as A)
		as PagedData
   WHERE RecordID BETWEEN (('+convert(nvarchar,@PAGE_INDEX)+' - 1) * '+convert(nvarchar,@PAGE_SIZE)+'  + 1)          
   AND ('  +convert(nvarchar,@PAGE_INDEX)+' * '+convert(nvarchar,@PAGE_SIZE)+');
   
	SELECT @TOTAL_COUNT=COUNT(*) FROM #temp2;


	SELECT @RECORD_COUNT=COUNT(*) FROM #temp3;

	SELECT *, @TOTAL_COUNT,@RECORD_COUNT from #temp4;
	
	DROP TABLE #temp1;
	DROP TABLE #temp2;
	DROP TABLE #temp3;
	DROP TABLE #temp4;';

	EXEC(@FINAL_QUERY);
END
GO
