CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_SBSCTN_FRM_RECORDID]
@USER_RECORD_ID int
AS
BEGIN

select SUBSECTION_NAME from HS_HR_IA_VENDOR_APPROVAL_INFO a LEFT JOIN HS_HR_IA_DASHBOARD_INFO b ON a.USER_RECORD_ID=b.RECORD_ID LEFT JOIN HS_HR_IA_SUBSECTIONS c ON b.SUBSECTION_ID=c.SUBSECTION_ID WHERE USER_RECORD_ID=@USER_RECORD_ID;

END
GO