CREATE OR ALTER PROCEDURE [QADBV9_L2].[SP_IA_GET_DATA_WITH_SUBSC_NAME]
@SUBSECTION_NAME varchar(200)
AS
BEGIN

SET NOCOUNT ON

Select a.MODULE_ID,SUBSECTION_ID,MODULE_NAME from HS_HR_IA_SUBSECTIONS a LEFT JOIN HS_HR_IA_MODULES b on a.MODULE_ID=b.MODULE_ID WHERE SUBSECTION_NAME=@SUBSECTION_NAME;

END
GO